- CHANGELOG.md
- manifest.json
- react/ProductPage.js
- react/queries/productsQuery.gql
Add billing policy and Remove redundant Spinner in ProductPage Component
**Secondary** Add categories prop on ProductPage
https://dev--storecomponents.myvtex.com/
> Add billing policy and Remove Spinner in ProductPage Component

- CHANGELOG.md
- manifest.json
- pages/pages.json
Add `vtex.my-orders-app` to store. 
To see my-orders page, you need sign in. 
https://login--storecomponents.myvtex.com/account/orders
> Integrate my-orders to store

- CHANGELOG.md
- manifest.json
- pages/pages.json
- react/AccountPage.js
Update AccountPage to use ExtensionContainer
Make `AccountPage` more flexible. 
https://dev--storecomponents.myvtex.com/
>  Update AccountPage to use ExtensionContainer

- CHANGELOG.md
- manifest.json
- pages/pages.json
- react/OrdersPage.js
Add account/orders route
This route is canonical. All stores must have.
> Add account/orders route

- CHANGELOG.md
- react/AccountPage.js
Add Fragment in AccountPage
Boticario store wants to import OrdersPage into AccountPage, and this solves the problem.
> Add Fragment in AccountPage

- CHANGELOG.md
- manifest.json
- pages/pages.json
Add `ExtensionContainer` to `store/login/container`. 
https://extension--storecomponents.myvtex.com/login
> Add ExtensionContainer to store/login/container

- CHANGELOG.md
- react/queries/productQuery.gql
Update graphql product query to support benefits retrievement.
The Benefits data of a Product are being added to the product data itself.
<a href="https://gustavo--storecomponents.myvtex.com/ninja-300/p">Workspace</a>
> Update graphql product query to support benefits retrievement.

- CHANGELOG.md
- pages/pages.json
- Add auth treament to the route of `/account` and `/account/orders`
- Add Loading component to Render Exports
[workspace link](https://claudivan2--storecomponents.myvtex.com/account)
> Add auth treatment to /account and /account/orders route

- CHANGELOG.md
- manifest.json
Bump my-orders beta version
SigIn in store and click in My orders
https://login--storecomponents.myvtexdev.com/account/orders
> Bump my-orders beta version

- CHANGELOG.md
- react/queries/productQuery.gql
- Fix circular product query
- When executing the query Product with the attribute benefits.items.product, cause a circular request query.
[workspace](https://claudivan3--storecomponents.myvtex.com)
1 - Go to Home Page
2 - Click in a product, the Product Page must be rendered without errors
> Fix circular product query

- CHANGELOG.md
- manifest.json
- react/queries/productQuery.gql
Go to a product page.
https://guilherme--extensions.myvtex.com/sms-provider/p
> Bringing benefitProduct back, after upgrade vtex.store@1.x in app-store

- CHANGELOG.md
- manifest.json
- react/ProductContextProvider.js
- react/cacheLocator.js
- react/queries/productPreview.gql
- react/queries/productQuery.gql
- react/queries/productsQuery.gql
Adds stale cache for product preview
> Stale cache for product preview

- CHANGELOG.md
- manifest.json
- react/queries/productQuery.gql
Add more information in product query
https://bruno--storecomponents.myvtex.com/
> Add more information in product query

- CHANGELOG.md
- manifest.json
- react/StoreContextProvider.js
Add the OrderFormContext
Now the BuyButton and Minicart share the same context
Linked to: [Previous PR](https://github.com/vtex-apps/store/pull/43)
[minicart](https://github.com/vtex-apps/minicart/pull/25), [buybutton](https://github.com/vtex-apps/store-components/pull/120)
[workspace](https://felipeoficial--storecomponents.myvtex.com/)
> OrderForm Context

- CHANGELOG.md
- manifest.json
- react/StoreContextProvider.js
- react/package.json
Add title and meta in store. These fields are available on admin settings
https://bruno--storecomponents.myvtex.com/
The fields are available on https://bruno--storecomponents.myvtex.com/admin/apps/vtex.store@1.5.1/setup
> Add title and meta in store. These fields are available on settings

- CHANGELOG.md
- manifest.json
- react/StoreContextProvider.js
Fix init data layer
When the store doesn't have the data layer, the push function explodes.
https://andre--storecomponents.myvtex.com/
* Bug fix (a non-breaking change which fixes an issue)
> Fix init datalayer

- CHANGELOG.md
- manifest.json
- react/HomeContextProvider.js
- react/ProductContextProvider.js
- react/ProductSearchContextProvider.js
- react/StoreContextProvider.js
- react/mutations/addToCartMutation.gql
- react/queries/orderFormQuery.gql
- react/queries/productPreview.gql
- react/queries/productQuery.gql
- react/queries/searchQuery.gql
Add meta tags in `ProductContext` and `SearchContext` providers
Add meta tags to SEO! 
**DISCLAIMER: This PR depends on next release of catalog stable version**
Navigate in https://bruno--storecomponents.myvtex.com/ and access the source HTML.
> Add meta tags in ProductContext and SearchContext providers

- CHANGELOG.md
- manifest.json
- react/ProductContextProvider.js
- react/ProductSearchContextProvider.js
Fix object undefined errors in dataLayer
https://bruno--storecomponents.myvtex.com/
> Fix object undefined errors in dataLayer

- CHANGELOG.md
- react/OrderFormContext.js
- react/mutations/updateItemsMutation.gql
Fix the update orderForm items function mutation.
There was an error when trying to remove an item from the orderForm.
https://waza2--storecomponents.myvtex.com/
> Fix the update orderForm items function

- CHANGELOG.md
- manifest.json
- react/helpers/searchHelpers.js
Add a guard in create map when Array was 0.
> Add a guard in create map when Array was 0.

- CHANGELOG.md
- README.md
- manifest.json
- react/HomeContextProvider.js
- react/ProductContextProvider.js
- react/ProductSearchContextProvider.js
Dispatch Datalayer events
The store wasn't dispatching events to the data layer.
https://andre--storecomponents.myvtex.com/ open browser console and type datalayer.
* New feature (a non-breaking change which adds functionality)
> Dispatch Datalayer events

- CHANGELOG.md
- manifest.json
- react/components/MicroData.js
Fix microdata variables
Some variables should be typed the first letter upper case.
https://andre--storecomponents.myvtex.com/nintendo-switch/p
* Bug fix (a non-breaking change which fixes an issue)
> Fix microdata variables

- CHANGELOG.md
- manifest.json
- react/queries/productQuery.gql
Update product query to get productClusters and clusterHighlights
> Update product query to get productClusters and clusterHighlights

- CHANGELOG.md
- manifest.json
- react/OrderFormContext.js
- react/ProductContextProvider.js
- react/mutations/updateOrderFormProfile.gql
Error handling when the product is not found
Better error handling
[workspace](http://searchhandler--storecomponents.myvtex.com/)
[#97](https://github.com/vtex-apps/store-graphql/pull/97)
>  Throw specific error when the product is not found on product resolver in catalog

- CHANGELOG.md
- manifest.json
- react/queries/productQuery.gql
Add recommendations products in product query
https://recommendations--storecomponents.myvtex.com/tv-sony/p
> Add recommendations in productQuery

- CHANGELOG.md
- react/queries/productQuery.gql
Add similars data in recommendations
The purpose is to get the similars data in Product Page
> Add similars data in recommendations

- CHANGELOG.md
- manifest.json
- react/StoreContextProvider.js
https://bruno--storecomponents.myvtex.com/admin/apps/vtex.store@1.17.0/setup
> Add metaTagRobots field in store settings

- CHANGELOG.md
- manifest.json
- react/ProductSearchContextProvider.js
Create a possibility to create a custom search.
https://fixsearch--storecomponents.myvtex.com/vitrineSecreta
* New feature (a non-breaking change which adds functionality)
> Add custom search schema

- CHANGELOG.md
- react/queries/productQuery.gql
- [storeComponents](https://github.com/vtex-apps/store-components/pull/171)
- [productDetails](https://github.com/vtex-apps/product-details/pull/55)
Add field variations values to productQuery
[workspace](https://felipe--storecomponents.myvtex.com/tenis-mizuno-wave-viper-3-masculino/p)
> Add field variations values to productQuery

- CHANGELOG.md
- manifest.json
- react/queries/productQuery.gql
https://bruno--storecomponents.myvtex.com/tenis-mizuno-wave-viper-3-masculino/p
> Update productQuery to get 10 sku images

- CHANGELOG.md
- manifest.json
- react/queries/searchQuery.gql
Fix preview from categories
Fix preview from categories
> Fix preview from categories

- CHANGELOG.md
- manifest.json
- react/ProductContextProvider.js
Fixing ProductNotFound Redirection and adding query param
Not Redirecting
https://cristalquebrado--storecomponents.myvtex.com/cd-magnificos/p
> Fixing ProductNotFound Redirection

- CHANGELOG.md
- manifest.json
- react/StoreContextProvider.js
- react/components/GtmScripts.js
Add `pageView` event on page change.
Some store's analytics weren't working properly.
[Workspace](https://lucas--storecomponents.myvtex.com/eletrodomesticos/d).
> Add pageView event to every page change

- CHANGELOG.md
- manifest.json
- react/ProductSearchContextProvider.js
Set absolute URL in canonical pages.
> Set absolute url in canonical pages

- CHANGELOG.md
- react/queries/orderFormQuery.gql
Query the clientProfileData firstName field
For `vtex.store-components/Greeting` to print a welcome message with the user name
> Add firstName field to orderFormQuery

- CHANGELOG.md
- manifest.json
- react/StoreContextProvider.js
https://bruno--delivery.myvtex.com look the source code of the page.
> Meta tag that disables zoom in mobile mode

- CHANGELOG.md
- manifest.json
- react/StoreContextProvider.js
Add an `ExtensionPoint` for the icon packs.
[Workspace](https://lucas--storecomponents.myvtex.com/eletronicos/d?map=c%2Cc&rest=Smartphones).
> Add extension container for icons

- CHANGELOG.md
- manifest.json
- react/mutations/updateOrderFormShipping.gql
- react/queries/orderFormQuery.gql
related to: https://github.com/vtex-apps/address-locator/pull/19
get more data on `orderForm` to help debug (not sure if should keep this)
fix param sent to mutation `updateOrderFormShipping`
> fix(updateOrderFormShipping): update mutation response

- CHANGELOG.md
- manifest.json
- react/HomeContextProvider.js
- react/ProductContextProvider.js
- react/ProductSearchContextProvider.js
- react/StoreContextProvider.js
Render runtime exports a new prefetch defaults function for rendering sync preview. This PR uses this new feature
> Using new prefetch defaults from render-runtime

- CHANGELOG.md
- manifest.json
- react/StoreContextProvider.js
Read more: https://dequeuniversity.com/rules/axe/2.2/meta-viewport
> Allow user scaling as recommended by accessibility guidelines

- react/StoreContextProvider.js
* [X ] Bug fix (a non-breaking change which fixes an issue)
> Fix canonical path encoding

- CHANGELOG.md
- manifest.json
- react/StoreContextProvider.js
Add ToastProvider to Store Context.
Components in the store can show a toast.
[Access this workspace](https://orderby--storecomponents.myvtex.com)
> Adding ToastProvider

- CHANGELOG.md
- manifest.json
- react/StoreContextProvider.js
Pass the query params to the service worker register request.
No way to programmatically set the debug service worker variable.
[Access the workspace](https://pwa--storecomponents.myvtex.com/?DEBUG_SW=true) and see the console
> Pass query params to service worker register request

- CHANGELOG.md
- manifest.json
- react/StoreContextProvider.js
Fix location evaluation to consider SSR
Location was undefined while SSR.
[Access the workspace](https://pwa--storecomponents.myvtex.com/?DEBUG_SW=true)
> Fix location evaluation to consider SSR

- CHANGELOG.md
- manifest.json
- react/StoreContextProvider.js
Fix URL query params evaluation
The `location && location.search` evaluation is wrong because returns `undefined`
[Access the workspace](https://pwa--storecomponents.myvtex.com/)
> Fix URL query params evaluation

- CHANGELOG.md
- manifest.json
- store/interfaces.json
As the title says 
https://version2--delivery.myvtex.com/
> Add `rebuy` and `address-locator` on interfaces

- CHANGELOG.md
- manifest.json
- react/queries/productPreview.gql
- react/queries/searchQuery.gql
This impacts the SEO analysis.
https://search--storecomponents.myvtexdev.com/shoes/d
> Remove description of the product to search query

- CHANGELOG.md
- manifest.json
- react/StoreWrapper.js
- react/utils/canonical.js
Makes necessary changes for canonicals to work with new pages
> Canonicals in Blocks

- CHANGELOG.md
- manifest.json
- react/components/IconPack.js
> Add loading svg on icon pack

- CHANGELOG.md
- manifest.json
- store/interfaces.json
- store/routes.json
https://bruno--storecomponents.myvtex.com/
> Minor changes in interfaces and routes

- CHANGELOG.md
- manifest.json
- react/ProfileChallenge.js
Fix a typo of setting state to `logged` instead of `loggedIn`.
This made the component render nothing, when the user was authenticated.
Access your account on [this workspace](https://lucas--storecomponents.myvtex.com/account).
> Fix typo on profile challenge

- CHANGELOG.md
- manifest.json
- react/StoreWrapper.js
- react/queries/pwaDataQuery.gql
**Depends on vtex/pwa-graphql#23**
Update the iOS icons query.
The pwa-graphql schema changed, so the store needs to be up to date
[Access the workspace](https://pwa--storecomponents.myvtex.com/)
> Update the iOS icons query

- CHANGELOG.md
- manifest.json
> Release v2.1.1

- CHANGELOG.md
- manifest.json
- store/interfaces.json
> add promo-bar extensible component to interfaces

- CHANGELOG.md
- manifest.json
- store/interfaces.json
> add hero-header to allowed

- CHANGELOG.md
- manifest.json
- store/interfaces.json
> rename to hero-header to info-card

- CHANGELOG.md
- manifest.json
- store/interfaces.json
> Remove related-products block from store.product

- CHANGELOG.md
- manifest.json
- store/interfaces.json
> remove info-card from interfaces

- CHANGELOG.md
- manifest.json
- react/ProductSearchContextProvider.js
- react/StoreContextProvider.js
- react/utils/capitalize.js
As the title says. 
https://store1--storecomponents.myvtex.com/shirt?map=ft
> Add search term in title tag and keywords on search pages

- CHANGELOG.md
- manifest.json
- store/blocks.json
- store/interfaces.json
Create a new interface to enable custom pages created by user
> Enable custom pages created by user

- CHANGELOG.md
- manifest.json
- react/SearchWrapper.js
- react/utils/capitalize.js
https://search--storecomponents.myvtex.com/shirt?map=ft
> Fix searchWrapper metatags

- CHANGELOG.md
- manifest.json
- react/utils/search.js
> Update translate label

- CHANGELOG.md
- manifest.json
- react/utils/search.js
> Sort by nothing

- CHANGELOG.md
- manifest.json
- store/interfaces.json
- store/routes.json
https://peer--storecomponents.myvtexdev.com
> Remove order-placed app because it does not work correctly with pixel architecture

- CHANGELOG.md
- manifest.json
- messages/context.json
- messages/en-US.json
- messages/es-AR.json
- messages/pt-BR.json
- react/StoreWrapper.js
- react/components/NetworkStatusToast.js
Show the network status so the user knows not all the store features are available.
Users don't know if they are online or offline.
[Access the workspace](https://netstatus--storecomponents.myvtex.com/)
> Network Status Toast

- CHANGELOG.md
- manifest.json
> Add vtex.store-components as a dependency

- CHANGELOG.md
- manifest.json
- store/interfaces.json
- store/routes.json
He's back, baby!
https://orderplaced--storecomponents.myvtex.com/
> Adding vtex.orderplaced again!

- .prettierrc
- CHANGELOG.md
- manifest.json
- react/StoreWrapper.js
Change from using children to props directly in the `Helmet` component.
For some reason, when using children in the helmet component instead of the actual props values _sometimes_ causes a "Maximum call stack size exceeded" error. :man_shrugging: 
This error was only being observed in the `beta` workspace of the vtexinstoredev account. [Workspace fixed](https://beta--vtexinstoredev.myvtex.com/instore/cart).
> Fix stack overflow error in helmet

- CHANGELOG.md
- manifest.json
- react/components/NetworkStatusToast.js
As title says.
[Workspace](https://klynger--storecomponents.myvtex.com/)
Before:
> Fix proptypes errors

- BLOCKS.md
- README.md
- STORE_BUILDER.md
To add documentation for the store builder.
> Add store builder documentation

- CHANGELOG.md
- manifest.json
- react/queries/productQuery.gql
- react/queries/productsQuery.gql
- react/queries/searchQuery.gql
> Add discountHighlights field in search and product queries

- CHANGELOG.md
- manifest.json
- store/interfaces.json
Allow notification bar
Depends: https://github.com/vtex-apps/store-components/pull/383
> Allow notification-bar

- CHANGELOG.md
- manifest.json
- store/interfaces.json
> Add `newsletter` as allowed block

- CHANGELOG.md
- manifest.json
> Update pwa-graphql version

- CHANGELOG.md
- react/queries/searchQuery.gql
A alteração feita é para adicionar as variações dentro de items
A mudança que foi feita, foi para poder ter acesso a variações na pagina de departamento onde esse arquivo esta sendo chamado.
Isso resolve a issue #204 
https://prntscr.com/n3qilw
* [x ] New feature (a non-breaking change which adds functionality)
> Add variations to searcheQuery

- CHANGELOG.md
- manifest.json
- react/queries/searchQuery.gql
https://variation--storecomponents.myvtex.com/
> Fix variations typo on searchQuery

- CHANGELOG.md
- manifest.json
- store/blocks.json
- store/interfaces.json
http://challenge--storecomponents.myvtex.com/account
> Fix access /account route without any challenge

- CHANGELOG.md
- manifest.json
- store/interfaces.json
Add support for product review interfaces.
Make it possible for a review app to be installed in the store.
Available in the workspace: https://breno--storecomponents.myvtexdev.com
1. Link this branch
2. Link the branch https://github.com/vtex-apps/product-summary/pull/145
3. Add to your theme:
```json
"store.product": {
"blocks": [
"product-rating-summary",
"product-details#default",
"product-kit",
"shelf.relatedProducts",
"product-reviews",
"product-questions-and-answers"
]
},
"product-summary.unstable--flex": {
"children": [
"product-summary-image",
"product-rating-inline",
"product-summary-price",
"product-summary-name",
"product-summary-description",
"product-summary-buy-button"
]
},
"search-result": {
"blocks": [
"filter-navigator",
"search-title",
"gallery",
"not-found", …
```
> Add support for product review interfaces

- CHANGELOG.md
- manifest.json
- react/ProductContext.js
Original [PR](https://github.com/vtex-apps/store/pull/223)
Test it [here](https://ituacu--storecomponents.myvtex.com/long-sleeve-shirt/p)
He made a fork, so in the release I would have to push to his repo, what would delay everything. As little as it is, I've decided that copying to a local branch was better
_Disclaimer:_ @ccamargo2294 did it, not @camilo (didn't know github tagged this)
> Redoing @Camilo's work

- CHANGELOG.md
- manifest.json
- react/SearchContext.js
- react/SearchWrapper.js
Use `productSearchV2` query.
[workspace](https://lucas--storecomponents.myvtex.com/shoes).
> Use new product search query

- CHANGELOG.md
- manifest.json
- messages/context.json
- messages/en.json
- messages/es.json
- messages/pt.json
- react/SearchContext.js
- react/components/NetworkStatusToast.js
> scope messages by domain

- CHANGELOG.md
- manifest.json
- react/SearchWrapper.js
> decode uri on search wrapper title

- CHANGELOG.md
- manifest.json
- react/utils/search.js
Test it [here](https://luciano--invictastores.myvtex.com/watch)
> Removing 'Sort By' option on OrderBy component

- CHANGELOG.md
- manifest.json
- react/SearchContext.js
> remove hideUnavailableItems usage for now

- CHANGELOG.md
- manifest.json
- react/ProductContext.js
- react/ProductWrapper.js
Uses new categoryTree field available in the store resources queries
> Use categoryTree

- CHANGELOG.md
- manifest.json
- react/SearchContext.js
https://fidelis2--storecomponents.myvtex.com/kawasaki/b
should work
> fix withFacets on productSearch

- CHANGELOG.md
- manifest.json
- react/CustomWrapper.js
- store/blocks.json
- store/interfaces.json
This will allow meta-tags on landing pages. 
https://meta--storecomponents.myvtex.com/banana
> Add CustomWrapper for custom pages

- CHANGELOG.md
- manifest.json
- react/SearchContext.js
- react/utils/search.js
> Use query string URL to create initial map if available

- CHANGELOG.md
- manifest.json
- react/SearchContext.js
https://fidelis2--storecomponents.myvtex.com/shirt?map=ft
Veja que ele pega uma camisa de cada vez.
> pass maxItemsPerPage to SearchContext children

- CHANGELOG.md
- manifest.json
- react/StoreWrapper.js
- react/queries/pwaDataQuery.gql
As the title says.
With the PWAContext, the `vtex.store` apps can use some PWA features ([See BuyButton]())
[Workspace](https://prompt--storecomponents.myvtex.com)
> Use PWAContext from store-resources

- CHANGELOG.md
- manifest.json
Allow stores to be completely CSR
We need to be faster for cold requests, we're working on it, but you might improve you performance in the meanwhile by trying out CSR.
> Add disableSSR setting to test CSR stores

- CHANGELOG.md
- manifest.json
Input descriptions were not helpful.
Make the UI cleaner.
https://breno--storecomponents.myvtexdev.com/admin/cms/storefront
Before | After
---|---
> Remove redundant descriptions from settings form

- CHANGELOG.md
- manifest.json
- react/ProductWrapper.js
https://analytics--storecomponents.myvtex.com/shirt/p?skuId=33
(See the console.log)
> Add `selectedSku` in productView event

- CHANGELOG.md
- manifest.json
- react/SearchContext.js
> reactivate hideUnavailableItems in SearchContext

- CHANGELOG.md
- manifest.json
- react/SearchContext.js
https://fidelis--invictastores.myvtex.com/disney?map=ft
or
https://fidelis--invictastores.myvtex.com/collections?map=c%2CspecificationFilter_69
look at breadcrumb & at search title
> clean params on SearchContext

- CHANGELOG.md
- manifest.json
- react/components/PageViewPixel.js
Add important info to pageview event.
The pixel iframe doesn't have this info.
https://breno--storecomponents.myvtex.com/clothing
n/a
> Add 'referrer' to 'pageView' event

- CHANGELOG.md
- manifest.json
- store/interfaces.json
https://github.com/vtex-apps/sandbox
> Add sandbox to allowed components

- react/__tests__/addToCartMutation.test.js
- react/__tests__/orderFormQuery.test.js
- react/__tests__/productQuery.test.js
- react/__tests__/productsQuery.test.js
- react/package.json
- react/setupTests.js
- react/yarn.lock
Remove dead code.
Remove misleading code.
Add vtex-test-tools.
Run `yarn install` and `yarn test` inside `react/`.
n/a
> Remove unused test structure

- CHANGELOG.md
- manifest.json
- react/StoreWrapper.js
As the title says.
Apparently, there are performance issues caused by not using this attribute.
[Workspace](http://defer--storecomponents.myvtex.com)
> Add defer attribute to /pwa/workers/register.js script tag

- BLOCKS.md
Remove comments and fix table of contents in `BLOCKS.md`
Broken/incomplete table of contents and unnecessary text.
> Remove comments and fix table of contents in BLOCKS.md

- CHANGELOG.md
- manifest.json
- react/StoreWrapper.js
Move the service worker to be default in the store.
[Workspace](https://thaylu--storecomponents.myvtex.com/)
> Add service worker by default in the store

- CHANGELOG.md
- manifest.json
> Add new setting requiresAuthorization

- CHANGELOG.md
- react/ProfileChallenge.js
Fix SSR error 
access here https://bruno--storecomponents.myvtex.com/account
> Make `getLocation()` of `ProfileChallenge` works on SSR.

- CHANGELOG.md
- react/SearchContext.js
> fix wrong boolean prop type

- CHANGELOG.md
- react/SearchContext.js
notar que:
https://fidelissearch--alssports.myvtex.com/Footwear/Sandals
é idêntico a:
https://alssports.myvtex.com/Footwear/Sandals
COnfirmar que fetch more funciona, que outras rotas funcionam, etc
Dependente da pr: https://github.com/vtex-apps/search-result/pull/194
> share SearchQuery component with LocalQuery on search-result

- react/package.json
- react/yarn.lock
> update ts version

- .prettierignore
- CHANGELOG.md
- react/ProductWrapper.js
https://fidelis--alssports.myvtex.com
> fix pdp when navigating from home

- CHANGELOG.md
- react/ProductWrapper.js
https://fidelis--alssports.myvtex.com/sitka-hoody-kelvin-lite-optifade/p?skuId=481171
> fix when selecting item in SKUSelector

- CHANGELOG.md
- react/ProductWrapper.js
Test cases:
https://fidelis--alssports.myvtex.com
- Navigate from home to an item, switch variations and see everything updates accordingly
- Click on another item from the recommended shelf, check that everything is OK, switch variations, add to cart
> reset pdp state when slug changes

- CHANGELOG.md
- store/routes.json
Adds optional id to routes with translatable terms
> Optional id to routes with translatable terms

- CHANGELOG.md
- store/routes.json
This reverts commit ce578ca6aa446abe3976c270be421aaf8d580906, reversing
changes made to 40fc6dc4adf250351ddbce7176a806aeb72c7be7.
> Revert "Merge pull request #296 from vtex-apps/revert/294"

- CHANGELOG.md
- react/ProductContext.js
> Adds id to product query in productContextProvider

- CHANGELOG.md
- manifest.json
> Release v2.39.0

- CHANGELOG.md
- manifest.json
- store/interfaces.json
https://fidelis--delivery.myvtex.com/pizza-pepperoni/p
> add sticky layout to allowed list

- CHANGELOG.md
- react/ProfileChallenge.js
- react/StoreWrapper.js
Test on `shop.samsung.com/ar?workspace=guilherme`
Generated on `view-source:https://shop.samsung.com/ar/galaxy-s10/p?workspace=guilherme`
`<link data-react-helmet="true" href="https://cdn.samsung.com/etc/designs/smg/global/imgs/favicon.ico" rel="icon"/><link data-react-helmet="true" rel="canonical" href="https://shop.samsung.com/ar/galaxy-s10/p"/>`
> Add rootPath to canonical URL and Profile Challenge

- CHANGELOG.md
- store/routes.json
Uses new store builder's feature of declaring a route with a contentType
> Add contentType to routes

- CHANGELOG.md
- store/routes.json
Since now we have rewriter in all store's accounts, we can remove the store's catch all route
> Removes the catch all route

- store/routes.json
This reverts commit 37e9a62f6ce810f52e07ea71a96fbeceed7162f1, reversing
changes made to cd85d1f2802121f8bfb40b51cf18e448c4767cd6.
> Revert "Merge pull request #319 from vtex-apps/feature/remove-catch-all"

- CHANGELOG.md
- react/ProductContext.js
make category tree resolver client side
https://bread--storecomponents.myvtex.com/classy--sunglasses/p
https://fidelis--exitocol.myvtex.com/celular-iphone-6s-64gb-rose-gold-100160624-mp/p
> use new product category tree query

- CHANGELOG.md
- react/StoreWrapper.js
Title set in StoreWrapper was overriding the one being set in SearchWrapper
https://bread--storecomponents.myvtex.com/shirt/p
https://fidelis--boticario.myvtex.com/cabelos
> move helmet from storewrapper to above

- CHANGELOG.md
- react/SearchContext.js
- react/SearchWrapper.js
https://fidteste--exitocol.myvtex.com/moda-y-accesorios/moda-nina/exterior-nina
view-source:https://fidteste--exitocol.myvtex.com/moda-y-accesorios/moda-nina/exterior-nina
see it returns with title as the name of the category from ssr
merge after graphql and resources
> use search metadata query with ssr

- CHANGELOG.md
- react/SearchWrapper.js
Before my final commit, I removed some lines and messed up a part, now fixing.
Title coming from SSR correctly (https://fidelis--boticario.myvtex.com/cabelos)
> fix search title

- CHANGELOG.md
- manifest.json
- react/StoreWrapper.js
Revert the removal of robots meta tag.
Clients want to configure it.
> Revert robots metatag

- store/blocks.json
- store/routes.json
This PR adds the new internal routes, that will allow for optimizations in the platform and translatable URLs
> New internal routes

- CHANGELOG.md
- react/ProductContext.js
Comments useNotFound line, for hotfix
> Removes useNotFoundx

- store/routes.json
Equal to https://github.com/vtex-apps/store/pull/335 that was reverted
This PR adds the new internal routes, that will allow for optimizations in the platform and translatable URLs
> New internal routes 

- store/routes.json
> Revert "New internal routes "

- CHANGELOG.md
- manifest.json
- store/interfaces.json
Allow `pickup-availability` on pdp
https://storek3--delivery.myvtex.com
> allow pickup-availability

- CHANGELOG.md
- manifest.json
- store/interfaces.json
https://badge--storecomponents.myvtex.com
> make stack-layout and product-specification-badges allowed

- manifest.json
- store/interfaces.json
Depends on https://github.com/vtex-apps/experimental__visibility-layout/pull/1
> Allow experimental__visibility-layout

- CHANGELOG.md
- manifest.json
- store/interfaces.json
To add `iframe` app to allowed on custom pages on store
> Added iframe to store.custom

- CHANGELOG.md
- manifest.json
- store/blocks.json
- store/interfaces.json
- store/routes.json
Add `/offline` route
We need this route to precache the `/offline` page to be shown when user is offline.
[Workspace](https://thay2--storecomponents.myvtex.com/offline)
Related: vtex-apps/pwa-components#5
> Add offline route

- CHANGELOG.md
- manifest.json
- store/interfaces.json
Allow new blocks related to lists to be used.
Enables users to use list blocks.
https://listcontexttest--storecomponents.myvtex.com/about-us
**DEPENDS ON**
- https://github.com/vtex-apps/product-summary/pull/198
> Allow list-context and product-list-block blocks

- CHANGELOG.md
- react/StoreWrapper.js
> Revert remove prefetch default pages

- CHANGELOG.md
- react/SearchContext.js
https://fidelis--storecomponents.myvtex.com/classic?_q=classic&map=ft
> support skusFilter

- CHANGELOG.md
- react/package.json
- react/yarn.lock
Linked workspace: http://ie11--storecomponents.myvtex.com/
> Use query-string@5 which supports IE11

- CHANGELOG.md
- manifest.json
> Release v2.79.2

- CHANGELOG.md
- react/SearchContext.js
As the title says.
Works along with:
https://github.com/vtex-apps/store-resources/pull/83
https://github.com/vtex-apps/search-result/pull/290
https://github.com/vtex-apps/search-graphql/pull/39
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/apparel---accessories/clothing/Black?map=c,c,specificationFilter_52)
> Add facetsBehavior

- CHANGELOG.md
- store/interfaces.json
Make it possible to add an iframe anywhere in the store.
https://breno--storecomponents.myvtex.com/
> Allow iframe on any page

- CHANGELOG.md
- react/StoreWrapper.js
- react/components/UserDataPixel.tsx
Observe no seu console log ele printando `teste PUSHING: {{dado}}`
https://fidelis--storecomponents.myvtex.com/
faça login e veja que seus dados são printados corretamente
> create user data pixel and push user data

- CHANGELOG.md
- manifest.json
- store/interfaces.json
Allow product-bookmark on PDP
https://breno--storecomponents.myvtex.com/classic-shoes/p
> Allow product-bookmark

- CHANGELOG.md
- react/SearchContext.js
https://skip--biscoind.myvtex.com/
> add simultaionBehavior param to searchcontext

- CHANGELOG.md
- store/blocks.json
- store/interfaces.json
- store/routes.json
Add `store.not-found#product` so we can have a "product not found" page.
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/)
> Added `store.not-found-product`

- CHANGELOG.md
- react/modules/search.js
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/home---decor/)
*Scores:*
- clock: 9999
- bell: 10
- vase: 5
- phone: 2
> Changed "Relevance" value to `OrderByScoreDESC`

- CHANGELOG.md
- store/routes.json
> Adds content type to product not found route

- CHANGELOG.md
- store/routes.json
This will allow the definition of the fallbacks strategies of routes.
> Add fallback entities to routes

- CHANGELOG.md
- manifest.json
- store/blocks.json
- store/interfaces.json
> Revert changes from #414

- CHANGELOG.md
- manifest.json
> Release without problematic code

- CHANGELOG.md
- manifest.json
> Undo order-placed workaround

- CHANGELOG.md
- manifest.json
- react/ProductContext.js
- react/components/OrderFormProvider.js
https://fidelis--alssports.myvtex.com/
> import queries and mutations directly

- manifest.json
- store/blocks.json
- store/routes.json
> Not found search block

- CHANGELOG.md
- manifest.json
Avoids accounts without store-indexer
> Adds store-indexer to dependencies

- .all-contributorsrc
- CODEOWNERS
- README.md
This automated pull request aims to:
- Add `all-contributors` to the project.
- Add `CODEOWNERS` with mentions to the store-framework dev team and the tech-writers team for `docs` changes.
> Add all-contributors and codeowners

- manifest.json
- store/blocks.json
> Adds 404 default page blocks

- CHANGELOG.md
- manifest.json
> Remove store-sitemap from peer deps

- CHANGELOG.md
- store/routes.json
**What is the purpose of this pull request?**
**What problem is this solving?**
The fallbackEntity is not the way we are going to use to identify routes anymore. So I am removing it
**How should this be manually tested?**
**Screenshots or example usage**
**Types of changes**
>  Removes fallback entities

- CHANGELOG.md
- react/components/MicroData.js
Fix issues with MicroData using ld+json code of vtex-apps/structured-data
1. Not rendering sku field
2. Not rendering all sku offers
https://brenovtex--brastemp.myvtex.com/freezer-vertical-brastemp-flex-frost-free-228-litros-bvr28mb/p?idsku=2003954&__disableSSR
```json
{
"@context": "https://schema.org/",
"@type": "Product",
"name": "Freezer Vertical Brastemp Flex Frost Free 228 Litros",
"brand": "Brastemp",
"image": "https://brastemp.vtexassets.com/arquivos/ids/192128/Brastemp_Freezer_BVR28MB_Imagem_Frontal--1-.jpg?v=636939534466130000",
"description": "O Freezer Vertical Brastemp Flex Frost Free, além de não precisar descongelar nunca, pode se transformar em uma geladeira sempre que precisar, isso porque conta com a tecnologia Flex. Possui também o Controle de temperatura externo, que …
```
> Use Structured Data code to render ld+json instead of MicroData

- CHANGELOG.md
- manifest.json
- Enables our clients to control the `enableCriticalCSS` settings via the admin.
go to:
https://css--storecomponents.myvtex.com/admin/cms/store
turn the setting on or off and check if it reflects on: https://css--storecomponents.myvtex.com
> critical setting

- CHANGELOG.md
- react/components/MicroData.js
- react/queries/productPreview.gql
- react/queries/productQuery.gql
Add spotPrice to store@1.x.
- Added the field spotPrice to the product query
- Updated the structured data with the changes from https://github.com/vtex-apps/structured-data/pull/24
https://brenovtex--brastemp.myvtex.com/geladeira-brastemp-inverse-maxi-573-litros-bre80ak/p
none
Depends on https://github.com/vtex-apps/store-graphql/pull/471
> Add field spotPrice

- CHANGELOG.md
- manifest.json
> Release v2.99.1

- CHANGELOG.md
- manifest.json
We have new advanced features that increase the store's performance but should be turn on carefully.  
Link this app, open the Admin, go to CMS, and then to Store. Now, go to the Advanced tab and check if the new items (Enables loading scripts asynchronously and React Concurrent Mode) are visible.
You can check if the flags are working by turning them on or off, saving, and checking if the values are correct (go to your terminal and run `vtex settings get vtex.store`).
> Add settings to enable Async Scripts and Concurrent Mode

- CHANGELOG.md
- manifest.json
Add a new performance setting that aims to improve the filters' performance
Open the admin, check the last setting and feel free to change it and see the search page's filters change!
[Admin](https://iaron--storecomponents.myvtex.com/admin/cms/store)
[Search Page](https://iaron--storecomponents.myvtex.com/apparel---accessories/clothing/)
> Add enableFiltersFetchOptimization setting

- CHANGELOG.md
- manifest.json
- react/SearchWrapper.tsx
- react/package.json
- react/yarn.lock
Improves the SEO of search pages by using product list structured data from 
https://github.com/vtex-apps/structured-data/pull/28
[Workspace](Link goes here!)
> Uses product list structured data

- CHANGELOG.md
- manifest.json
Search and custom pages are slow for some stores, and we have new features that increase these pages' performance.
This Pull Request makes these features available through store configuration and allows our users to turn them on.
Link this branch, go to `admin/cms/store`, open the Advanced tab and check if `Critical CSS Optimization on Search Page`  and `Critical CSS Optimization on Custom Page` are available. 
Or just take a look at this workspace.
https://bacelar2--marinbrasil.myvtex.com/admin/cms/store
> Add Advanced Settings for Critical CSS on Search and Custom pages

- CHANGELOG.md
- manifest.json
Add flag on store settings.
CMS/Store/Advanced.
X
X
X
> Add pdp critical css flag

- CHANGELOG.md
- manifest.json
update manifest.json with new translations paths
> update manifest.json with new translation paths

- CHANGELOG.md
- crowdin.yml
Update Crowdin file for crowdin integration
> Update Crowdin file

- CHANGELOG.md
- react/SearchWrapper.tsx
[Workspace](https://thalyta1--storecomponents.myvtex.com/)
- search for a product. e.g: "shirt"
- Search for a second product using a misspelled name
- check the term sent to event-api
https://user-images.githubusercontent.com/20840671/162290706-6245ec31-33b8-4a60-b14d-d4dcc9970ab7.mp4
https://user-images.githubusercontent.com/20840671/162290753-e6f64c67-c6cb-48c3-a6c2-8bd29e67ae79.mp4
> Fix term in pixel event

- CHANGELOG.md
- docs/README.md
- manifest.json
This reverts changes introduced by #538.
Check that the `Advanced` tab still works at: [Workspace](https://victormiranda--alssports.myvtex.com/admin/cms/store).
https://github.com/vtex-apps/store/pull/538
> Revert PR #538

- CHANGELOG.md
- messages/ar-SA.json
- messages/context.json
- messages/en.json
- messages/no-NO.json
- messages/th-TH.json
- messages/th.json
Add Thai translations and add EN and context messages for previously hardcoded strings rendering in other apps. Tracked by task [LOC-8204](https://vtex-dev.atlassian.net/browse/LOC-8204) and connected to this [other PR](https://github.com/vtex/builder-hub/pull/1150).
> Add TH and fix hardcoded strings

- CHANGELOG.md
- react/SearchContext.jsx
add sponsoredProductsBehavior flag to the SearchContext
> add sponsoredProductsBehavior flag

- CHANGELOG.md
- messages/th.json
Fix Thai translation. It relates to https://github.com/vtex-apps/store/pull/585 and [LOC-16364](https://vtex-dev.atlassian.net/browse/LOC-16364)
[LOC-16364]: https://vtex-dev.atlassian.net/browse/LOC-16364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix thai translation

- CHANGELOG.md
- react/StoreWrapper.js
https://docs.google.com/document/d/1J5EOAPh4PFeuPDItUla_l4t4JaA9cZOTE1EGd-XuC5g/edit?tab=t.0
> feat: add storefront meta tag to StoreWrapper

- CHANGELOG.md
- messages/pl.json
Add Polish translation
https://polish--inpostfresh.myvtex.com/admin
> Add polish translation

- CHANGELOG.md
- manifest.json
- react/typings/vtex.render-runtime.d.ts
- store/contentSchemas.json
This PR addresses the need for controlled migration to semantic HTML elements for accessibility improvements without breaking existing implementations, enabling compliance with the **European Accessibility Act (EAA)** that came into effect in June 2025.
The EAA requires digital services, including e-commerce platforms, to meet accessibility standards based on **WCAG 2.1 Level AA** and **EN 301 549**. Key requirements that this flag helps implement include:
- **Semantic HTML structure**: Proper use of heading hierarchy (`<h1>`, `<h2>`, etc.) and form labels
- **Programmatic relationships**: Proper association between labels and form controls using `htmlFor` attributes
- **Screen reader compatibility**: Ensuring assistive technologies can properly navigate and understand content structure …
> [STR-737] feat: add a11ySemanticHtmlMigration accessibility feature flag
