vtex-apps/store

CHANGELOG.md, manifest.json, react/ProductPage.js, react/queries/productQuery.gql
* Pass product object down to product page children.
* Add a few attributes to the product query.
* The product page children did not know which product they were representing.
* The app store needed those attributes.
=> Pass down product object on product page

CHANGELOG.md, pages/pages.json, react/SearchPage.js
- Pass some props that are missing in the ExtensionPoint inside SearchPage
- Fix the problem in the SSR of search-result app
[workspace link](https://claudivan--storecomponents.myvtex.com/Eletronics?O=OrderByBestDiscountDESC&Q=Smartphones&map=c%2Cc&page=1)
=> Fix SearchPage ExtensionPoint props

CHANGELOG.md, react/CategoryPage.js, react/queries/productQuery.gql
Add more data on `productQuery.gql`
**Secondary** Passing props for `ExtensionPoint` at CategoryPage
https://store--storecomponents.myvtex.com/ninja-300/p
=> Add more data on productQuery

CHANGELOG.md, manifest.json, react/queries/productQuery.gql
Add `categoriesIds` field on productQuery
=> Add categoriesIds field on productQuery

CHANGELOG.md, react/SearchPage.js, react/constants/propTypes.js, react/constants/searchSortOptions.js, react/helpers/searchHelpers.js, react/queries/facetsQuery.gql, react/queries/searchQuery.gql, react/queries/searchResultQuery.gql
Add the SearchResult's GraphQL queries to the project so the data layer can get them.
Lack of information to populate the data layer
[Access the workspace](https://estacio--storecomponents.myvtex.com/eletronics/s)
=> Add the SearchResult's GraphQL queries to the SearchPage

CHANGELOG.md, react/ProductPage.js, react/StoreTemplate.js, react/components/withDataLayer.js
On the product page, add the product details data to the data layer array.
[Access this workspace](https://datalayer--storecomponents.myvtex.com/ninja-300/p) and see the `dataLayer` array on the console.
=> Add data layer to product page

CHANGELOG.md, manifest.json, pages/pages.json
We had a serious problem yesterday.
Routes like: `/api/billing/contracts` were being served by render-server due to paths like `/:department/:category/:subcategory` in which nothing is "fixed". 
It should be rendered by colossus-legacy-proxy (which is the last possible match)
By adding a hint to the end of the url we can prevent this behavior.
=> add hints to the end of category or subcategory paths

CHANGELOG.md, pages/pages.json, react/DepartmentPage.js, react/components/SearchQueryContainer.js
Add the `DepartmentPage` component and fix search loading logic inside the `SearchQueryContainer` component.
1. There was no `DepartmentPage`
2. There was no way to know if the query result was the first one or the real data one.
[Access the workspace](https://estacio--storecomponents.myvtex.com/eletronics/d)
=> Add the DepartmentPage component and fix search loading state

CHANGELOG.md, react/components/SearchQueryContainer.js, react/constants/propTypes.js, react/helpers/searchHelpers.js
Change reverse path evaluation to not use pages.json
Helper was using pages.json
[Access the workspace](https://estacio--storecomponents.myvtex.com/eletronics/d)
=> Change reverse path evaluation to not use pages.json

CHANGELOG.md, react/helpers/searchHelpers.js
Fix params evaluation when there is no page path.
`treePath` is not being passed to the `ExtensionComponent`, so we need to be able to evaluate the page without the `treePath` and use only the `params`
[Accessing the workspace](https://estacio--storecomponents.myvtex.com/vehicles/d)
=> Fix params evaluation when there is no page path.

CHANGELOG.md, manifest.json, react/ProductContextProvider.js, react/ProductSearchContextProvider.js, react/components/DataLayerWrapper.js, react/components/ProductDataLayer.js, react/components/ProductSearchDataLayer.js, react/components/SearchQueryContainer.js, react/helpers/dataLayerHelper.js, react/helpers/searchHelpers.js
Data layer integration in the `ProductSearchContextProvider` and fix the `searchHelpers.reversePagesPath` function to return the full path.
There was data layer integration only in the `ProductContextProvider` and the `searchHelpers.reversePagesPath` function was returning invalid values to be used inside the `vtex.search-result/SearchResult`
[Access the workspace](https://estacio--storecomponents.myvtex.com/eletronics/d)
=> Data layer integration in the ProductSearchContextProvider

CHANGELOG.md, manifest.json, react/ProductSearchContextProvider.js
Add check for existence of `searchQuery` before accessing it's properties.
Error on accessing prop that doesn't exists.
[Workspace](https://lucas--storecomponents.myvtex.com/samsung/s?map=ft).
=> Fix undefined prop access

CHANGELOG.md, manifest.json, react/components/SearchQueryContainer.js, react/helpers/searchHelpers.js
Delete all unnecessary path manipulation to not need pages information.
Before this, there was some pages information inside the search helpers.
[Access the workspace](https://estacio--storecomponents.myvtex.com/eletronicos/d) and see it is working
=> Delete all unnecessary path manipulation to not need pages information.

CHANGELOG.md, manifest.json, react/StoreContextProvider.js, react/scripts/gtm.js
Enable google tag manger use in all store pages.
1. Link `vtex.store` and configure some gtm identification accessing the admin path `admin/apps/vtex.store@1.3.1/setup`
2. Navigate in the store and check if `google tagmanager` script was injected on page.
=> Provide Google Tag Manager native support

CHANGELOG.md, manifest.json, react/ProductSearchContextProvider.js, react/components/SearchQueryContainer.js
Refactor some of the handling of the query and fix the query not working due to an extra `/` at the end of the query.
When you clicked on a filter on the search results page, the filter weren't being applied.
[Workspace](https://lucas--storecomponents.myvtex.com/eletronicos/s).
=> Fix search result filters not working

CHANGELOG.md, manifest.json, react/ProductContextProvider.js
Add conditions before accessing properties on the product.
Not all properties are available on the product object, so on a store that don't have a product with all fields filled it would break the page when it tried to add to the data layer.
=>  Fix error when destructuring product properties 

CHANGELOG.md, pages/pages.json, react/HomeContextProvider.js, react/StoreContextProvider.js
- Fix Data Layer to be recreated after each page change
- Create HomeContextProvider to push to the data layer when the user it's in the home page.
The data layer is the same in the entire store, once the `StoreContextProvider` it's only created once. Each page pushes to it, causing an object different in many contexts.
Access: https://andre--storecomponents.myvtex.com
Open the browser console and type `datalayer`.
=> Fix Data Layer refresh + HomeContextProvider

CHANGELOG.md, manifest.json, pages/pages.json
Search paths(`/d, /c, /sc, /s`) doesn't have sufix anymore.
=> Remove sufixes from routes that are not ambiguous

CHANGELOG.md, react/ProductContextProvider.js, react/ProductSearchContextProvider.js
Change the props passed to the Breadcrumbs and add it to the SearchResult page.
Now the breadcrumbs component can be used on the SearchResult page.
[workspace](https://felipeoficial--storecomponents.myvtex.com/eletronicos/computadores/c)
[breadcrumbs](https://github.com/vtex-apps/breadcrumb/pull/9)
=> Change breadcrumbs props

CHANGELOG.md, manifest.json, react/OrderFormContext.js, react/mutations/updateOrderFormProfile.gql
Add the update profile data mutation to the OrderFormContext
We need to set the profileData of the orderForm to impersonate a customer
[workspace](https://felipe--storecomponents.myvtex.com)
=> Add update profile data mutation

CHANGELOG.md, react/queries/searchQuery.gql
---
Depends on vtex-apps/store-graphql#104
---
Update the search query so it includes the new fields `Id` and `Slug` on the appropriate types.
The query was outdated.
=> Update search query to include Id and Slug

CHANGELOG.md, manifest.json, react/ProductSearchContextProvider.js, react/queries/productQuery.gql
Referenced Pull Requests:
- https://github.com/vtex-apps/store-graphql/pull/115
Add SKU data to the benefit in the `productQuery` and fix products is `undefined` error on ProductsSearchContext.
Improvement the benefits data in order to bring the information about what SKU items composes each benefit. Fix application error.
<a href="https://productkit--storecomponents.myvtex.com/">Click here to access the workspace</a>
=> Add SKU data to the benefit in the `productQuery` and fix products is undefined error on SearchContext

.eslintrc, CHANGELOG.md, manifest.json, pages/pages.json, react/ProductContextProvider.js
Fix undefined categories prop in ProductContextProvider
Also, `my-orders-app` is embedded in `my-account`, this makes the route `account/orders` useless.
https://store--storecomponents.myvtex.com/
=> Fix undefined categories prop in ProductContextProvider

CHANGELOG.md, manifest.json, react/ProductSearchContextProvider.js, react/utils/search.js
Change the default of mapping the params to a category type to mapping each one to it's own corresponding type.
On a brand page (such as [this one](https://storecomponents.myvtex.com/google/b)), the query is being made with a category type, instead of brand, which results in no product being found, thus all the products are returned from the api.
[Workspace](https://lucas--storecomponents.myvtex.com/google/b).
=> Fix query on brand page with wrong arguments

CHANGELOG.md, react/OrderFormContext.js, react/mutations/updateOrderFormShipping.gql, react/queries/orderFormQuery.gql
*NOTE:* This PR is dependant on [store-graphql#134](https://github.com/vtex-apps/store-graphql/pull/134) approval
Adds `shippingData` to the orderForm context query and enables updating the shipping with the function `updateORderFormShipping`
For the app `address-locator` and `delivery-dreamstore`, we need to be able to read and update the shippingData, with the purpose of changing the delivery address.
On any app that has the HOC `vtex.store/OrderFormContext`, check that it can now read shippingData values and update it with `props.orderFormContext.updateOrderFormShipping`
=> Feature(orderForm): query shippingData and create updateOrderFormShipping mutation

CHANGELOG.md, manifest.json, react/ProductContextProvider.js
It fixes product preview.
We use `readFragment` to get cached product data directly from apollo storage and enable rendering a preview while we wait for product query completion.
But `readFragment` does not grant that every fragment field will be loaded. This creates an issue when we provide incomplete product data to children components, that crashes when trying to access some missing fields. It is happening right now if the recommendations query finishes before the product query, adding an incomplete product data to apollo storage and leading to this error.
=> Fix partial product preview (naively)

CHANGELOG.md, manifest.json, react/Queries.js, react/queries/sessionQuery.gql
Other modules may want to use vtex.store's queries. This PR enables this functionality by exporting all queries in an entrypoint and adding a new `Sessions` query
Link this module along with [telemarketing](https://github.com/vtex-apps/telemarketing/pull/11) and [login](https://github.com/vtex-apps/login/pull/67) and use the session functionalities
=> Export store's queries to allow import in other modules

CHANGELOG.md, manifest.json, react/OrderFormContext.js, react/queries/orderFormQuery.gql
Enable querying of `availableAddresses` in `orderFormQuery`
The needing of [address-locator](https://github.com/vtex-apps/address-locator) component to have functionalities using the available addresses
=> Enable querying of availableAddresses in orderFormQuery

CHANGELOG.md, manifest.json, react/queries/orderFormQuery.gql
Adds field `clientProfileData.email` to `orderFormQuery`
`vtex.rebuy` needs to know the user email from orderForm to get his last order from MasterData
N/A
Used for this PR: https://github.com/vtex-apps/rebuy/pull/1
=> Query email on orderForm

CHANGELOG.md, manifest.json, react/ProductSearchContextProvider.js
Add field `orderBy` to context schema.
You couldn't set the default order by option before.
[Workspace](https://lucas--storecomponents.myvtex.com/eletronicos/d).
=> Add field orderBy to schema

CHANGELOG.md, manifest.json, react/ProductSearchContextProvider.js, react/StoreContextProvider.js, react/package.json, react/utils/canonical.js, react/utils/search.js, react/yarn.lock
Move the insertion of `<link rel="canonical" />` to the store context, so it's applied to all pages.
The canonical url existed only in the search pages.
[Workspace](https://canonicalpath--storecomponents.myvtex.com/iphone-xs).
=> Move canonical url to store context

CHANGELOG.md, manifest.json, react/ProductSearchContextProvider.js, react/queries/searchQuery.gql
Add option to the search query, so the client is able to skip the `facets`.
See [vtex/store-graphql#169](https://github.com/vtex-apps/store-graphql/pull/169).
=> Add option to search query to exclude facets

CHANGELOG.md, manifest.json, react/StoreContextProvider.js
This PR prevents the browser's history from showing system routes on client-side navigation. It does so by replacing these routes with canonical urls. For example, if we navigate to 
Depends on: https://github.com/vtex-apps/render-runtime/pull/163
`/my-favorite-brand/b`, this route will be replaced with `/my-favorite-brand`
Many people have complained about having the `/b, /d, /s` in the end of conflicting routes. This PR address this problem by artificially replacing these terminations with their canonical representations
=> replace system routes to use canonicals

CHANGELOG.md, manifest.json, react/StoreContextProvider.js
Include the `history.location.search` in the path replaced.
On department screens, the path replaced removed the query parameters.
[Workspace](https://lucas--storecomponents.myvtex.com/decoration).
=> Fix canonical path replace

CHANGELOG.md, manifest.json, react/StoreContextProvider.js
Add missing space before charset definition.
The value without the space is considered invalid by the AMP Validator.
**⚠️ Caution:** here be dragons, [workspace](https://lucas--storecomponents.myvtex.com/clothing?__amp).
=> Fix http-equiv meta tag content

CHANGELOG.md, react/queries/productQuery.gql
Query the productReference field and provide it to ProductContext
The app `vtex.product-details` at the current stable version (`0.8.3`) has an option on it's schema to show the reference of the product, but it's not rendered because it never gets the necessary data to pass as props to `vtex.store-components/ProductName`.
https://dan--schuster.myvtex.com/gabinete-para-bomba-de-vacuo/p
=> Add missing productReference field to the query

CHANGELOG.md, manifest.json, react/StoreWrapper.js
Replace the usage of the old context api (using `contextType`) to use the function provided in the `runtime` prop.
This will give a warning when running in strict mode.
=> Remove usage of old context API

CHANGELOG.md, react/ProductWrapper.js, react/components/MicroData.js
- Add skuId in microdata offer and product,
- Allow that only the sellers who have the match with the skuId can sell an item. 
https://mdsku--storecomponents.myvtex.com
1. Go to the [google test tool](https://search.google.com/structured-data/testing-tool) and paste the source code from the [storecomponent(master)](https://storecomponents.myvtex.com/basic-t-shirt/p?skuId=2000525) in left side. Run the the test. Switch between the skus.
2. Note that has an a warning indicating the miss of a sku
3. Do the steps above again with this [workspace](https://mdsku--storecomponents.myvtex.com/basic-t-shirt/p?skuId=2000525) and realize the output.
=> Microdata offer and seller varies from skuId

CHANGELOG.md, manifest.json, react/components/MicroData.js
Render all the sku's like a offer's microdata. 
https://mdsku--storecomponents.myvtex.com/
Go to the  [google test tool](https://search.google.com/structured-data/testing-tool) and paste the source code from the page of a product (the product needs have more than one sku). Note that has more than one field offer.
=> All sku should be an offer in microdata

CHANGELOG.md, manifest.json, react/StoreWrapper.js, react/package.json, store/interfaces.json
Create the interface that will allow `admin-pages`' Storefront to insert the `HighlightOverlay` plugin, which highlights the selected component.
This broke when migrating to the new blocks architecture.
=> Highlight overlay on store

CHANGELOG.md, manifest.json, styles/iconpacks/iconpack.svg
Change the loading symbol to be an actual loading spinner.
The icon wasn't the right one.
Link this branch in any workspace.
Before
After
(the gif isn't smooth, but _trust me_)
=> Fix loading icon

CHANGELOG.md, manifest.json, styles/iconpacks/iconpack.svg
Change from `className` to `class` on iconpack svg.
The attribute `className` is specific to javascript and doesn't work on the svg.
=> Fix className on svg file

CHANGELOG.md, manifest.json, react/utils/search.js
The default order by should be by relevance of the search or the default of the category.
=> Add default orderBy to relevance

CHANGELOG.md, manifest.json, react/StoreWrapper.js
Users can now configure their store's favicons in the Store settings and StoreWrapper adds these links.
There wasn't any way to configure favicons before.
=> Favicon Settings

CHANGELOG.md, manifest.json, store/interfaces.json
As the title says.
The address-locator is a different sort of component now—not inserted on every page as a bar and modal, but rather a single page component. Its previous role is now fulfilled by the `user-address` component, located in the `store-components` app.
=> Remove address-locator dependency

CHANGELOG.md, manifest.json
This PR adds store-sitemap as a peer dependency of `vtex.store`
This means that, to install `vtex.store`, `vtex.store-sitemap` will have to be installed. 
I think this behavior is ok, since `vtex.store-sitemap` is the one having the canonical routes translation map and is a must have for our stores
=> Adds store-sitemap as peer dependency of store

CHANGELOG.md, manifest.json, react/components/NetworkStatusToast.js
**Depends on vtex/styleguide#581**
Without the `toastState` from the `ToastContext`, we cannot determine whether there is no Toast been shown to show the offline toast. This way, when a toast pops up and then goes away, the offline toast can pop up again.
The offline toast should appear when there is no other toast been shown.
[Access the workspace](http://toast--storecomponents.myvtex.com) and open the dev tools and click the `Network > Offline` option (or turn off your device's network). Then click the buy button to see the offline toast be replaced but when the buy button toast goes away, the offline toast goes up again.
=> Add the toast persistence logic as we know if there is a toast visible.

CHANGELOG.md, manifest.json, react/StoreWrapper.js
Related PR, should be released after this one: [render-runtime](https://github.com/vtex-apps/render-runtime/pull/272)
Test [here](https://cafedovento--storecomponents.myvtex.com/) using our search, changing the sort option, and going back. It didn't work before.
**Why is this necessary**
For some routes, we have two paths, one being the main one and the other being a canonical path, declared like this on _routes.json_
```javascript
"store.search#brand": {
"path": "/:brand/b",
"canonical": "/:brand"
}
```
This is part of the mecanism to make possible the user navigate to `/shoes`, _shoes_ being a category, and get that page relative to a _category_. When someone accesses `/shoes/c` for the first time we save that registry and `/shoes` is now a category path, and we redirect now a user that …
=> Passing navigationRoute and fetchPage false for the canonical replace

CHANGELOG.md, manifest.json, react/SearchWrapper.js
Get the title tag and meta tag description values from the search property *inside* the data.
These values weren't being retrieved from the correct object, thus making the title and meta description not reflecting the current page values.
[Workspace](https://lucas2--storecomponents.myvtex.com/decoration/tvs).
=> Fix search title and meta description not working

CHANGELOG.md, manifest.json, react/StoreWrapper.js
Add guard before mapping splash screens.
=> Add guard for splash screens

CHANGELOG.md, manifest.json, react/ProfileChallenge.js
Test it on [ituacu](https://ituacu--storecomponents.myvtex.com/account#/profile)
Related [story](https://app.clubhouse.io/vtex-dev/story/3600/follow-the-returnurl-param)
Before this, if you navigate to `/account#/orders` and wasn't logged in, the redirect would occur with the `returnUrl=%2Faccount`, losing the hash, that identifies a specific page on `my-account`.
=> Append the hash to the returnUrl

CHANGELOG.md, manifest.json, react/SearchContext.js
To pass only the category (map `c`) and full text (map `ft`) to the facets query.
Stable filters feature, see vtex-apps/search-result#150.
[Workspace](https://lucas--storecomponents.myvtex.com/clothing/shirts?map=c%2Cc).
=> Use only category and full text to facets query

CHANGELOG.md, manifest.json, react/SearchWrapper.js
fix: https://app.clubhouse.io/vtex-dev/story/10295/product-name-is-encoded-on-search-title
=> decode uri when getting page title on searchwrapper

CHANGELOG.md, manifest.json, store/routes.json
Add a new field to store routes: `map`
We need to support legacy routes using `map` query string. For instance `/smartphones/Blanco?map=c,specification_filter39` should be a filtered *department* page but is identified as a *category* page because it matches the path `/:department/:category`.
The new `map` field will be available to do a proper route matching in pages-graphql and render-runtime.
Depends on: https://github.com/vtex/builder-hub/pull/549
=> Add 'map' to store routes

CHANGELOG.md, manifest.json, react/components/NetworkStatusToast.js
As the title says...
On mobile devices, the toast was overlaying the buy button. Now it can be dismissed.
[Access the workspace](http://offline--storecomponents.myvtex.com)
=> NetworkStatusToast is now dismissable on mobile devices

CHANGELOG.md, manifest.json, react/StoreWrapper.js, react/package.json, react/utils/canonical.js, react/yarn.lock
Remove canonical discovery and  history replacement code from `vtex.store`
Canonical paths will now be handled by `render-runtime` itself. This will make everything simpler as we won't need to do a double history push/replace.
For instance, `render-runtime` navigates to `/department/d` then `vtex.store` code changes it to `/department`.  Now `render-runtime` will set the path directly to `/department`, making our history manipulation sane 🙏 
Depends on https://github.com/vtex-apps/render-runtime/pull/291
=> Remove canonical discovery and history replacement

CHANGELOG.md, manifest.json, react/components/PageViewPixel.js, react/yarn.lock
Fix referrer in pixels.
Referrer was being passed when the value was like:
`https://storetheme.vtex.com/checkout`
Since it did not match with
`https://storetheme.vtex.com/`
(the origin)
n/a
n/a
=> Fix document referrer when is the same origin

CHANGELOG.md, manifest.json, react/StoreWrapper.js
Remove the `v` query with `Date.now()` from the manifest url.
This fixes multiple manifests being added to the page `head`, because the query render prop was being executed several times, and each time it rendered the `Helmet` added a new manifest to the page, because of the different query strings.
[workspace](https://lucas2--storecomponents.myvtex.com/?__debugSW).
=> Fix multiple manifests added to the page

CHANGELOG.md, manifest.json, react/StoreWrapper.js
Prepend the `rootPath` on the PWA-related routes.
When the store is configured with a root path (e.g. `/ar`), the pwa routes inserted into the page were directed to `/pwa/*path`, but in fact they should be `/ar/pwa/*path`.
[workspace](https://lucas2--storecomponents.myvtex.com/)
=> Add rootPath on pwa routes

CHANGELOG.md, manifest.json, store/interfaces.json
Show the heart icon of wish list in product details.
In product details screen doesn't show the heart icon to add product in wish list.
[workspace](https://thaynan--storecomponents.myvtex.com/)
=> Show the heart icon of wish list in product details

CHANGELOG.md, manifest.json, react/SearchWrapper.js
Fix SEO issues.
Google is indexing search results when it shouldn't.
Search for something in the search bar, verify if it has the meta tag robots with the value "noindex,follow". Categories and department pages should have "index, follow".
https://breno--storecomponents.myvtexdev.com/top/s?map=ft
=> Add robots meta tag with "noindex,follow" when it's a search result

CHANGELOG.md, manifest.json, react/ProductWrapper.js
Add Open Graph to product page.
With Open Graph social networks like: Facebook can add rich previews to product page link.
Also, some integrations like Facebook Pixel and Bluecore read those tags natively.
Open:
https://breno--storecomponents.myvtexdev.com/classic-shoes/p
Look for the Open Graph meta tags, like: `og:type`, `product:brand`, etc.
=> Add Open Graph to Product page

CHANGELOG.md, react/SearchContext.js, react/package.json, react/yarn.lock
https://fidelis--alssports.myvtex.com/145/s?map=productClusterIds
- See that it appears here.
- See that in categories pages it is not broken: https://fidelis--alssports.myvtex.com/hunting/Shooting/Accessories?map=c%2Cc%2Cc
=> only filter for c and ft facets on tail of query and map array.

CHANGELOG.md, react/queries/searchQuery.gql
Add product properties to Search Results to Store v1 (Our client Naturitas it's right now on store v1)
Our clients want display some product properties on Search Result,  and this is the only way.
1. Go to search results page and check all it's fine, and the SearchQuery Props have properties on array products.
2. APP its linked in this workspace: https://pmartin--naturitasit.myvtex.com/cosmetica-e-igiene/cura-del-corpo/esfoliante-per-il-corpo
=> Add Product properties on SearchQuery

CHANGELOG.md, store/interfaces.json
Require header.full as `before` block of every store page
Custom pages are not required to have `header.full`, just `header`. So you can end up with different headers on theses pages if you don't explicitly use `header.full`. It can be confusing because they may look similar (depending on your blocks.json) but the treePath and therefore content will be different.
Link any theme with a custom page and browse the custom page. `__RUNTIME__.extensions[__RUNTIME__.page].before` will give you `[$before_header]`
Link this branch and then link the theme again (ctrl-c + `vtex link`), now you have:
`__RUNTIME__.extensions[__RUNTIME__.page].before` = `[$before_header.full]`
=> Require header.full as `before` block of every store page

CHANGELOG.md, manifest.json, store/interfaces.json
Make it possible to do https://github.com/vtex-apps/store-theme/pull/153
Allow to use a new block.
[Workspace](https://breno3--storecomponents.myvtex.com/long-sleeve-shirt/p)
~Depends on publish https://github.com/vtex-apps/product-identifier first.~ published
=> Add product-identifier to PDP

CHANGELOG.md, store/routes.json
Adds /:slug/p as product canonical. This PR makes possible to have internal product urls without the user noticing in the url history
=> adds /:slug/p as product canonical

CHANGELOG.md, store/interfaces.json
Make it possible to add a search-result in store.custom.
Make it possible to create this page:
https://www.eriksbikeshop.com/eriks-bicycle-buying-guide.aspx
https://breno--storecomponents.myvtex.com/about-us
=> Allow search-result to store.custom

react/SearchWrapper.js
Stop decoding titleTag
`titleTag` does not need any decoding. The text is already the way it should be. When calling `decodeURI` we are throwing an error if the text contains something like `50% OFF`.
```
> decodeURI('50% OFF')
VM162:1 Uncaught URIError: URI malformed
at decodeURI (<anonymous>)
at <anonymous>:1:1
```
It is breaking the page.
=> Stop decoding titleTag

CHANGELOG.md, manifest.json, store/interfaces.json
Add store blog pages needed by vtex.wordpress-integration
For the Wordpress integration app (and any future blog integrations) vtex.store now defines page interfaces for store.blog-home, store.blog-post, store.blog-category, and store.blog-search-result . 
A separate app, vtex.blog-interfaces, defines abstract interfaces for the block components of these pages.
Example blog pages can be seen here:
https://wordpresstest--storecomponents.myvtex.com/blog
https://wordpresstest--storecomponents.myvtex.com/blog/category/410
https://wordpresstest--storecomponents.myvtex.com/blog/post/13189
https://wordpresstest--storecomponents.myvtex.com/blog/search/tim%20clarke
=> Add various blog pages in conjunction with vtex.blog-interfaces

CHANGELOG.md, react/ProductContext.js
~Fix the props passed down from ProductContext.~
Remove stray props passed down from ProductContext.
This also fixes the usage of the interface `sandbox` in the product page, since that interface uses a `safe-json-stringify`, when this lib tried to stringify the props I think it was falling into a cycle making the browser tab to stop (ouch).
I changed from `Object.assign` call to object spread the wrong way (I use to err on that a lot)
https://github.com/vtex-apps/store/commit/6f7fa240a4c18522c1cc0a386493c7a37ff3ec7d#diff-0aa7635b08024e9103931440d4c59db7R106
https://breno--storecomponents.myvtex.com/classic-shoes/p
**Props Before**
Notice that there are `props` and `breadcrumbProps` there.
**Props After**
Removed props `props` and `breacrumbProps`.
=> Fix ProductContext props passed to children

CHANGELOG.md, react/ProductWrapper.js, react/SearchWrapper.js
Change the suffix used on product pages and search pages.
The suffix used nowadays is the "Default title tag", which can be a bit misleading since it's the title used both as a fallback and as the suffix for the pages mentioned above. This PR makes the store name the suffix added to the title.
[Workspace](https://storename--storecomponents.myvtex.com/)
1. Change the "Store Name" and the "Default title tag" on [the Store Settings](https://storename--storecomponents.myvtex.com/admin/cms/storefront).
2. Access a [product page](https://storename--storecomponents.myvtex.com/shirt/p) and check the suffix..
3. Access a [search page](https://storename--storecomponents.myvtex.com/apparel---accessories/hats/) and check the suffix.
4. Access a [page without …
=> Use storeName instead of titleTag on page title.

CHANGELOG.md, react/utils/search.js
Make "relevance" the default orderby
The current default orderby is "sales" when it was supposed to be "relevance"
[workspace](https://iaronaraujo--alssports.myvtex.com/clothing/Jackets/Womens?map=c%2Cc%2CspecificationFilter_7721)
=> fixed default orderby on searches

CHANGELOG.md, manifest.json, store/interfaces.json
Allow to add product-teaser-interfaces to the product page.
Integrate with https://docs.affirm.com/Integrate_Affirm/Promotional_Messaging
https://breno--storecomponents.myvtex.com/work-shirt/p
=> Allow product-teaser.product

CHANGELOG.md, react/SearchContext.js
Open a department page
https://storecomponents.myvtex.com/apparel---accessories/
Click on Kawasaki
Check that the URL have `/25/` and I didn't filter by Kawasaki
Do the same thing here:
https://breno--storecomponents.myvtex.com/apparel---accessories/
=> Fix issue when filtering in a department page

CHANGELOG.md, react/StoreWrapper.js
Add store.search to prefetch default pages
=> Add store.search to prefetch default pages

CHANGELOG.md, store/interfaces.json
`blog-breadcrumb` has been added as an allowed block on blog pages.
This is an additional feature that I've developed for the Wordpress integration (`vtex.wordpress-integration`).
View example page here: https://wordpress--worldwidegolf.myvtex.com/insider/post/13260
(blog breadcrumb is at top of page)
=> Added blog-breadcrumb as allowed block on blog pages

CHANGELOG.md, manifest.json, react/HomeWrapper.js, react/StoreWrapper.js
Adding Google Search Box script in the head to show the input search for the store in google search
go to https://vtexcamilo--exitocol.myvtex.com/ in the elements should be with the script
=> Add Google Searchbox script to head in Storewrapper

CHANGELOG.md, manifest.json, react/SearchWrapper.js, react/StoreWrapper.js
Remove the `keywords` field  from `manifest.json` since it isn't used by [Google](https://youtu.be/jK7IPbnmvVU
) and other search engines for almost a decade, as pointed by @rgoytacaz.
Useless field that only adds noise.
[Home](https://nokeywords--storecomponents.myvtex.com/)
[Site Editor](https://nokeywords--storecomponents.myvtex.com/admin/cms/site-editor)
=> Remove keywords metatag

.gitignore, CHANGELOG.md, react/StoreWrapper.js, react/yarn.lock
This PR removes the meta tags with an empty `content=""` property, and adds the `<link rel="amphtml">`, to link the AMP page.
This makes possible for the google crawler to discover the store AMP pages.
Linked in [this](https://lucas--delivery.myvtex.com/) workspace.
=> Fix empty meta tags and add link for amphtml

CHANGELOG.md, react/StoreWrapper.js
Removes the `amphtml` helmet link.
Google Search Console was emitting an error saying the page wasn't a valid AMP page. We initially released this because we didn't know there was a problem in always linking to the `amphtml`.
[Workspace](https://lucas--delivery.myvtex.com/)
=> Remove amphtml link

react/ProductWrapper.js, react/__mocks__/vtex.product-context/ProductContextProvider.js, react/__mocks__/vtex.product-context/useProduct.js, react/__tests__/ProductWrapper.test.js, react/__tests__/StructuredData.test.ts, react/components/StructuredData.js
Move logic related to ProductContext to its own app.
Fix tests, only test title related data at ProductWrapper
Add basic tests to structured data.
To test: navigate to PDP
https://fidelis--storecomponents.myvtex.com/
=> remove product context logic, use provider from app, fix tests

CHANGELOG.md, manifest.json, store/interfaces.json
Allow `vtex.tab-layout`'s blocks on `store`.
Allows users to create tabbed layouts on store pages.
See https://tablayout--storecomponents.myvtex.com/ for a working example
=> Add tab-layout interfaces

CHANGELOG.md, manifest.json, store/interfaces.json
Add `slider-layout` to allowed blocks on the `store` interface.
https://sliderlayout--storecomponents.myvtex.com/about-us
This page uses 3 `slider-layout` blocks, each of them with a different children type.
=> Add slider-layout to allowed components

CHANGELOG.md, manifest.json, react/StoreWrapper.js
Google Analytics load time apparently includes prefetching assets, *even if they're done 20 seconds after load happens.* :kaotico:
This is a test to check whether load time improves without prefetching the other pages. 
Load times as measured by Google Analytics.
=> Remove prefetch default pages for test purposes

CHANGELOG.md, manifest.json, store/interfaces.json
Add `image-slider` block from `vtex.store-image` to allowed blocks at `store` interface.
This should allow our users to use the new interfaces implemented by `vtex.store-image` app.
The first slider at
https://imageslider--storecomponents.myvtex.com/about-us is an `image-slider`.
**THIS SHOULD ONLY BE RELEASED AFTER**
- https://github.com/vtex-apps/slider-layout/pull/7
- https://github.com/vtex-apps/store-image/pull/3
=> Allow `image-slider` block

CHANGELOG.md, react/__tests__/ProductWrapper.test.js, react/components/ProductTitleAndPixel.tsx
If categoryTree came as [], it would crash.
Add protection and test for it.
=> protect against empty category tree on product page

CHANGELOG.md, manifest.json, store/interfaces.json
All the new `responsive-layout` blocks to be used.
It allows users to define layout blocks that will only be rendered on certain breakpoints.
https://victorhmp--storecomponents.myvtex.com/about-us
=> Add `responsive-layout` to allowed list

CHANGELOG.md, react/SearchContext.js
Add support for `preventRouteChange` on non-custom search result pages.
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/apparel---accessories/clothing?map=c,c,specificationFilter_52&query=/apparel---accessories/clothing/Blue)
Needs https://github.com/vtex-apps/search-result/pull/259 to work properly
=>  Prevent Route Change

react/SearchWrapper.js
Fixed stable loading for searches' setQuery. This brings back the double spinner issue though.
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/)
Open a search or category and watch that when you change a facet or ordination type the loading is still as it was previously.
=> First implementation of search loading fix

CHANGELOG.md, manifest.json, store/interfaces.json
Enable users to use the `menu` block in every interface extending `store`, such as `store.home`.
The `menu` could only be used inside the `header` block.
Notice that there is a menu right below the Shelf:
[Workspace](https://menustore--storecomponents.myvtex.com/)
Should solve this: https://app.clubhouse.io/vtex/story/26033/allow-menu-on-store-home
=> Allow `menu` on `store` interface

CHANGELOG.md, manifest.json, react/StoreWrapper.js
Add new contexts from `vtex.order-manager` to the `StoreWrapper` component so that they can be consumed by components created by the checkout-ui team. This is also necessary for the new minicart@3.x and `vtex.add-to-cart-button`.
Without those two contexts, `add-to-cart-button` and `minicart@3.x` would not work :( .
[Workspace](minicart--storecomponents.myvtex.com)
=> Use new OrderFormProvider and OrderQueueProvider contexts

CHANGELOG.md, store/routes.json
Renames the offline page from `/offline` to `/_v/offline`.
As discussed internally, we agreed that "offline" may be the name of some brand, and could cause conflicts with this route, so we decided to change it to refer to an internal route.
[Workspace](https://lucas2--storecomponents.myvtex.com/)
=> Rename offline page route

CHANGELOG.md, manifest.json, react/StoreWrapper.js
Use `OrderFormProvider` and `OrderQueueProvider` from `vtex.order-manager`.
This enables apps to use these new contexts, which use the new `checkout-graphql`.
[Workspace](https://minicart--storecomponents.myvtex.com/)
=> Use contexts from `vtex.order-manager`

CHANGELOG.md, react/StoreWrapper.js
Check for service worker support in the current browser _before_ adding the script to register the service worker to the page. This will also change the server-side rendering behaviour, so the script can only be added in the client-side now.
Browsers that do not have the service worker capabilities won't benefit from downloading this script at all, so it's just wasted network resource at this point. Also, they may throw a syntax error for some ES6 features we are using (such as arrow functions, and `const` and `let` declarations), and this will prevent just that.
You can access the changes in [this workspace](https://lucas2--storecomponents.myvtex.com/)
=> Check for support before adding register SW script

CHANGELOG.md, manifest.json, store/interfaces.json
Add `add-to-cart-button` to the allowed list for `store.product` interface.
This enables the `add-to-cart-button` block to be used inside of a PDP.
[Workspace](https://minicart--storecomponents.myvtex.com/classic-shoes/p)
=> Add add-to-cart-button to allowed list for store.product

CHANGELOG.md, store/interfaces.json
Apparently custom wrapper is not defined anymore as a component and doesn't need to be exposed in interfaces.json
It confuses people on how to use custom blocks.
=> Remove custom wrapper from interfaces.json

CHANGELOG.md, react/SearchWrapper.tsx
Fix bug of hanging loading between search page transitions.
Fix the last version of vtex.store.
Before:
1. Open https://brenobug--exitocol.myvtex.com/
2. Click in Mercado, page loads properly
3. Hover Mercado and click in "Salsas Condimentos y Sopas"
4. Should show a hanging loading state
Fixed:
1. Open https://breno--exitocol.myvtex.com/
2. Click in Mercado, page loads properly
3. Hover Mercado and click in "Salsas Condimentos y Sopas"
4. Page should load properly
=> Fix hanging loading screen between loading pages

CHANGELOG.md, react/StoreWrapper.js, react/__tests__/navigation.test.js, react/package.json, react/utils/navigation.js, react/yarn.lock
Add navigation normalisation with `path.toLowerCase` and sort of `specificationFilters`
Merge after: [https://github.com/vtex-apps/render-runtime/pull/455](url)
This logic was implemented in render runtime. It makes sense to be here since it's a logic specific to stores.
1 - open: https://jey--alssports.myvtex.com
2 - navigate to any category on the menu
3 - select any filter at the sidebar
4 - check the url, specificationFilters should be sorted and path should be lowercase
=> Navigation path normalisation

CHANGELOG.md, store/routes.json
Since we can have more than 3 categories, the subcategory canonical path should reflect that.
=> Adds *terms to subcategory canonical

CHANGELOG.md, react/__tests__/navigation.test.js, react/utils/navigation.js
Separate URL normalization on navigate for new and legacy search URLs
The idea here is to maintain compatibility between our current search URL structure `/foo/Bar?map=c,specificationFilter_1` and our new one `/foo/nice_Bar`. 
At the current URL structure we apply a lowerCase function whenever the segment is nos a specificationFilter and we also sort everything that's not category.
At our new URL structure we keep lowerCasing stuff, but there are segments we wan't to keep static, soo we've added, getIgnoredSegments, this happens with the specFilter, `/foo/nice_Bar`, case where we should maintain it's case.
=> New search urls

CHANGELOG.md, manifest.json, react/package.json, react/yarn.lock
Shift the dependency on `vtex.order-placed@1.x` to `vtex.order-placed-1-x-copy@1.x` to avoid circular dependencies caused by https://github.com/vtex-apps/order-placed/pull/93 .
This is needed in order to publish the new version of `vtex.order-placed` that depends on `vtex.store@2.x`.
[Eicom](https://orderplacedfix--eicom.myvtex.com/checkout/orderPlaced)
[Boticario](https://victormirandatest--boticario.myvtex.com/checkout/orderPlaced)
[TBB](https://victormirandatest--tbb.myvtex.com/checkout/orderPlaced)
=> Workaround

CHANGELOG.md, react/StoreWrapper.js
When configured with relative path, like `/arquivos/favicons.ico`, we have to append the rootpath of the store to properly display the favicon, result would be `us/arquivos/favicons.ico`
https://wwwuat.motorola.com/us/?workspace=fidbeta
https://www.als.com/?workspace=fidbeta still works
=> fix favicon for stores with relative favicon and root path

CHANGELOG.md, manifest.json, react/HomeWrapper.js
This new key is used in the component structured-data for set the search term for the robots of google
Add new attribute for store settingsSchema
Allow the configuration of the saerch term for google search
Yes
=> Add new key `searchTerm` in the settingsSchema

CHANGELOG.md, react/utils/navigation.js
Filter navigation tells store to not normalize it's filters, because the search is case sensitive.
Add a navigation normalization option to disable lowercase. 
Should be merged after: https://github.com/vtex-apps/search-result/pull/309
=> Navigation normalization option to disable lowercase

CHANGELOG.md, manifest.json, react/StoreWrapper.js, react/package.json, react/yarn.lock
Adding a new `enableOrderFormOptimization` setting to the app, which enables users to control whether or not the "legacy" `OrderFormProvider` (the one that does not use `checkout-graphql`) is rendered by the `StoreWrapper` component.
This should enable stores to be faster by not having two different orderForms being loaded.
1. Go to [Workspace with enableOrderFormOptimization = `true`](https://victorhmp--storecomponents.myvtex.com/), where this setting is set to `true`.
2. Open Apollo DevTools and check the queries being performed to render the page. You should see only one mention of `orderForm`, which is a query performed by the *new* OrderFormProvider to `checkout-graphql`.
3. Go to [Workspace with enableOrderFormOptimization = …
=> Add `enableOrderFormOptimization` setting to the app

CHANGELOG.md, store/routes.json
This issue is a regression we had. It is happening because we’ve made a change to support category trees with length greater than 3, the max was 3 before. The canonical calculation was simpler though, any path with size greater than 3 was discarded. 
This PR places this behaviour back and will remove canonicals with path greater than 3. There should be additional effort later to improve canonical calculation logic.
Look for the canonical at, it should be: https://jey--eriksbikeshop.myvtex.com/cycling/bicycles/road
https://jey--eriksbikeshop.myvtex.com/cycling/bicycles/road/Dropbar?map=c,c,c,specificationFilter_254
=> Remove *terms of subcategory canonical template

CHANGELOG.md, react/__tests__/navigation.test.js, react/utils/navigation.js
We apply a normalization, i.e lowercasing path segments when navigating. Search URLs filters can't be lower cased because the search result index is case sensitive. The normalization ignores paths relatives to specificationFilters. However, as we've changed URL structure for specification filters, removing from querystring and only passing them through the path, with the format `filterName_filterValue`, we can't read this information anymore.
This PR removes the lowercasing when the URL follows the new format structure. i.e `filterName_filterValue`
1 - When navigating trough the menu in worldwidegolf any link under apparel/Men's categories.
You will notice that the filter is getting lowercased and the results are empty.
https://worldwidegolf.myvtex.com
Repeat the same steps above for this …
=> Remove navigation normalization for new search URLs

CHANGELOG.md, react/SearchContext.js
Currently, VTEX has its own protocol between the search API and the UX components. This protocol forces new search-engines to implement specific rules to communicate with the UX. The [`search-protocol`](https://github.com/vtex/search-protocol) project purposes a generic way to make the UX/API communication.
This PR adds 4 props that are essential for new search engines.
Three of them behave like `page` and it appears in the URL as queryStrings. They are `fuzzy`, `operator` and `searchState`.
The other one, `__unstableProductOriginVtex`, doesn't have a relation with the URL.
You can check the definition of each one in the [`search-protocol`](https://github.com/vtex/search-protocol) project.
Navigate to a fulltext search, click on the facets or the fetch more button to see the URL changing. …
=> add new props

CHANGELOG.md, store/routes.json
User routes will be supported by render as rewriter internal routes.
They will have the following pattern /_v/segment/routing/vtex.store@2.x/userRoute/:id/*tems where id and terms are routeId and pathId respectively.
This PR enables rewriter to understand this route format for store.
Open:
https://jey--storecomponents.myvtex.com/_v/segment/routing/vtex.store@2.x/userRoute/vtex.store@2.x:store.custom::renato/renato
It should open a custom landing page for the route `/renato`
=> Add `store.custom` route template

CHANGELOG.md, manifest.json, store/contentSchemas.json
It's not possible to translate the title tag and the description of the store. To do that we need to make the type of `titleTag` and `metaTagDescription`  as `app:vtex.native-types#/definitions/text`, but `settingsSchema` doesn't support this, so we are moving this settings to a `contentSchemas`.
https://github.com/vtex-apps/store-discussion/issues/269
(This workspace should be working after all the other apps responsible to the changes have it deployed](https://github.com/vtex-apps/store/pull/449)
* In order for this to work the CMS team has to make some changes.
* The definition in `settingsSchema` will only be removed after everything is working using the `contentSchemas` definition
* [] Bug fix (a non-breaking change which fixes an issue)
=> Copy settingsSchema do contentSchemas

CHANGELOG.md, react/ProductContextProvider.js, react/components/MicroData.js, react/package.json, react/yarn.lock
Read `idsku` and `skuId` query string to render product Microdata
Rendering MicroData from another SKU that is unavailable.
Open:
https://brenovtex--brastemp.myvtex.com/maquina-de-bebidas-brastemp-b-blend-com-purificador-roxo-bpg40c2/p?idsku=3260201241
Open Elements tab o Chrome Dev Tools e look for "schema"
The current schema in production:
=> Read `idsku` and `skuId` query string to render product Microdata

CHANGELOG.md, react/ProfileChallenge.tsx
Fix redirect after login. 
`navigate` from render-runtime [parses the query string](https://github.com/vtex-apps/render-runtime/blob/master/react/utils/pages.ts#L108) and is [no longer re-encoding it](https://github.com/vtex-apps/render-runtime/pull/380). Since the `returnUrl` query string needs to be encoded for the redirect to work, the `navigate` method had to be replaced.
1. Without login into your store account, try reaching this page: https://challenge--recorrenciaqa.myvtex.com/account#/orders
- it should redirect you to log in.
2. After logging in, you should be redirected to the URL above.
=> Replace navigate with location.assign

CHANGELOG.md, react/modules/searchMetadata.test.ts, react/modules/searchMetadata.ts, react/modules/searchTypes.ts
Extend the information provided by the `pageInfo` event when inside search pages, which will include a bit more information about the query that can be used by VTEX Intelligent Search and other 3rd party search providers to help gather analytics info about the queries being executed.
Gather analytics information, in VTEX Intelligent Search's case, this is stored and used to provide usage reports, conversion metrics, and boost popular products.
Check the value stored in `window.pixelManagerEvents` on both workspaces below:
- `vtex.search-resolver@0.x`: https://christian--storecomponents.myvtex.com/shirt?_q=shirt&map=ft
- `vtex.search-resolver@1.x`: https://christiansearch--storecomponents.myvtex.com/shirt?_q=shirt&map=ft
- Using `vtex.search-resolver@0.x`:
- Using …
=> Add operator, searchState and correction to SearchMetadata

CHANGELOG.md, react/components/ProductTitleAndPixel.tsx
Add more data to productView event to be able to implement Klaviyo pixel app.
1. Open: https://breno2--storecomponents.myvtex.com/wood-clock/p
2. Check `pixelManagerEvents` variable in dev tools
3. Open the `productView` event
=> Add imageUrl and detailUrl to productView event

CHANGELOG.md, manifest.json, react/StoreWrapper.js
A website can only have one Service Worker registered and we provide one by default.
Some stores have another Service Worker provided by a third party service, like OneSignal. 
This setting makes it possible to disable ours, so third party Service Workers may function.
https://brenoswon--storecomponents.myvtex.com/
https://brenoswoff--storecomponents.myvtex.com/
none
Depends on https://github.com/vtex/pwa-graphql/pull/87
=> Add setting to disable Service Worker

CHANGELOG.md, react/ProfileChallenge.tsx
Second attempt of https://github.com/vtex-apps/store/pull/460, this time taking `rootPath` into consideration.
See related PR #460 and #462 
I'll publish a beta version to test it in a production workspace (with zero traffic) in a store that uses rootPath, since rootPath is never added when in myvtex.com
=> Fix login redirect

CHANGELOG.md, react/modules/searchMetadata.test.ts, react/modules/searchMetadata.ts, react/modules/searchTypes.ts
When building the search metadata, we are using the `productSearch.breadcrumb` to get the search term. The problem is that intelligent search uses `facets.breadcrumb` instead of `productSearch.breadcrumb`. I could add the facets' breadcrumb as a fallback, but I preferred to use the `productSearch.queryargs` field because I think it is more related to metadata info.
[Workspace](https://hiago--storecomponents.myvtex.com/top?_q=top&map=ft)
Access a full-text search and then type `window.pixelManagerEvents` on the console.
=> use queryArgs instead of breadcrumb to get search metadata term

CHANGELOG.md, react/SearchWrapper.tsx, react/typings/vtex.render-runtime.d.ts
To understand better the problem look at https://github.com/vtex-apps/store-discussion/issues/349
**To test `Show More` and `orderBy` change**
[Als workspace](https://pixelsearch--alssports.myvtex.com/gloves?_q=gloves&map=ft)
1. [Workspace](https://pixelsearch--storecomponents.myvtex.com/apparel---accessories)
2. Check how many events are triggered already putting `pixelManagerEvents` into the console
3.  Make the action (change the `orderBy`  in the `SORT BY` dropdown or click show more
4. Check the size of events again, it should have a new `pageinfo` event triggered, it might have something else, but it doesn't matter
5. The `orderBy` or the `page` should be different if compared with the previous `pageinfo` event
To test filter changes just select a filter and check the events
=> Add orderBy and page to trigger pageinfo event

CHANGELOG.md, react/SearchWrapper.tsx
The `internalSiteSearchView`event depends on the `facets` query, but sometimes, the message is sent before this query is completed. This PR makes sure that this event will only be sent when the query is completed.
[Workspace](https://hiago--xiaomimx.myvtex.com/redmi%20note%209?map=ft)
=> add queryArgs validation

CHANGELOG.md, react/components/ProductTitleAndPixel.tsx
We need the product's sellerName in a new event of our Pixel App.
[Workspace](https://gus--carrefourbr.myvtex.com/smartphone-samsung-galaxy-s10-128gb-branco-4g-tela-6-1-camera-tripla-16mp-selfie-10mp-dual-chip-android-9-0-5666287/p#product-info-anchor)
=> New property `sellerName` in product pixel event

CHANGELOG.md, react/SearchContext.js, react/SearchWrapper.tsx, react/utils/decodeForwardSlash.ts
Currently, it is not possible to search for a term that contains "/" because it is not being encoded. For example, if you search for `3-48m/s br nl` the result will be the following
It is not possible to encode the "/" with "%2F" because of [this](https://github.com/vtex/rewriter/blob/872e028b814de2ade81917dd73cb16f1394a29d1/node/utils/paths.ts#L21) function that will guarantee that no encoded term will pass.
My team and I decided to use another sequence of characters to encode it: `$2F`.
[Workspace](https://searchslashbug--storecomponents.myvtex.com/top$2fs?map=ft
I've tried really hard to keep the usual "code" for the `/`. But while   [this](https://github.com/vtex/rewriter/blob/872e028b814de2ade81917dd73cb16f1394a29d1/node/utils/paths.ts#L21) function is in the rewriter it will be …
=>  decode forward slash

CHANGELOG.md, manifest.json
We have new advanced features that increase the store's performance but should be turn on carefully.  
Link this app, open the Admin, go to CMS, and then to Store. Now, go to the Advanced tab and check if the new items (Enables CSS Concatenation, Enables Prefetch, and Enables Lazy Runtime) are visible.
You can check if the flags are working by turning them on or off, saving, and checking if the values are correct (go to your terminal and run `vtex settings get vtex.store`).
=> Add new performance flags to the settings schema

CHANGELOG.md, react/SearchContext.jsx
New props added to `SearchContext` component:
- `excludedPaymentSystems`
- `includedPaymentSystems`
These props enable users to pass these two arguments to the search query performed by `store.search` pages.
Go to this [workspace](https://victormiranda--storecomponents.myvtex.com/apparel---accessories/).
Depends on https://github.com/vtex-apps/store-resources/pull/134.
=> Add new props to SearchContext

CHANGELOG.md
Dependency route leaking.
More details: https://github.com/vtex/builder-hub/pull/991 https://github.com/vtex/colossus/pull/305
Unfortunately, the `vtex deps update` does not work anymore. But there is a version released using the new builder-hub here: https://brunoh--storecomponents.myvtex.com/ and it works fine.
=> Fix dependency route leak

CHANGELOG.md, manifest.json, react/ProductWrapper.js
There is a new feature flag called `enableFullSSROnProduct` (https://github.com/vtex/render-server/pull/691) to make the product page run in the render-ssr, allowing other graphql queries to be executed besides the product one.
Unfortunately many custom components do not care about the loading state, and apollo, even with the product data already restored in its memory cache (from render-server), render at first with no data and loading=true, making our `userProduct` hook return a `null` product and crashing any component that doesn't handle it well.
`vtex.render-server` and this `vtex.store` are linked here, with `enableFullSSROnProduct=true`:
https://pdpssrdev--dzarm.myvtex.com/calca-jeans-super-skinny-com-elastano-cintura-media-zu5v1asn/p
and here is the error in the same scenario but …
=> Prevent SSR crash when product data is loading

CHANGELOG.md, react/modules/search.js
Our default `orderBy` would not follow the default behavior from the Search API, as we always set the default to `OrderByScoreDesc`. A big problem that came up is that it was not possible to just present the products in the same order as they were placed inside their collections.
This new `OrderByDefault` is the one that is interpreted by our search resolvers as "don't send any orderBy and let the API handle that".
Go to this [Workspace](https://victormiranda--cosmetics1.myvtex.com/6008?map=productClusterIds).
- https://github.com/vtex-apps/search-result/pull/442
=> Update default 'orderBy' option to 'OrderByDefault'

CHANGELOG.md, react/SearchWrapper.tsx
When the title tag had a percentage symbol (`%`) an error was occurring when trying to run decodeURIComponent(titleTag)
[Before](https://raissateste--acctglobal.myvtex.com/141?map=productClusterIds)
[Workspace](https://testedecodeuri--acctglobal.myvtex.com/141?map=productClusterIds)
=> Fix title tag with percentage

CHANGELOG.md, react/modules/search.js
We're removing the `Default` sorting option introduced by #496 in favor of changing the way the `Relevance` ordering works. It will now follow the same behavior defined by the Search API.
Go to [Workspace](https://victormiranda--cosmetics1.myvtex.com/6008?map=productClusterIds) and check that the orderBy is set to `Relevance`, and the products are ordered the same way they are [here](https://cosmetics1.vtexcommercestable.com.br/6008?map=productClusterIds).
Depends on: https://github.com/vtex-apps/search-result/pull/452.
=> Bring back order by "Relevance" as the default value

CHANGELOG.md, react/SearchContext.jsx
[Workspace](https://searchstate--iocea.myvtex.com/moda-feminina/blusas)
- set the `searchState` of the `sessionStorage`. 
ex: `sessionStorage.setItem('searchState', '{"rcs":"1","sessionId":"1","userId":"1"}')`
- reload the page and check if the url contains the `searchState` that you set.
- you can also check if the `FilterNavigator` has the state:
=> Use searchState of the sessionStorage

CHANGELOG.md, react/ProductWrapper.js, react/SearchWrapper.tsx, react/StoreWrapper.js
Make it possible to create custom global context in pages.
1. Create a React component in the root directory of the `react` folder
Example:
```tsx
/* MyCustomContext.js */
import React from 'react'
import MyContext from './modules/MyContext'
function MyCustomContext({ children }) {
return <MyContext.Provider value={123}>{children}</MyContext.Provider>
}
export default MyCustomContext
```
2. Create an interface for it in the `store/interfaces.json` file.
Example:
```json
{
"my-custom-context": {
"component": "MyCustomContext",
"composition": "children"
}
}
```
There are 3 page wrappers available:
Wrapper | Pages available | Contexts available
---|---|---
`storeWrapper` | All pages | [`useOrderForm`](https://github.com/vtex-apps/order-manager), …
=> Add CustomContext prop in page wrappers

CHANGELOG.md, react/__tests__/navigation.test.js, react/utils/navigation.js
Since Intelligent Search doesn't have the same facet name as SOLR, the URL order is not following the category/brand hierarchy. This PR fixes this problem.
- Go to the workspace
- Click on the `Cafetiere` category
- Check the breadcrumb order. On the broken workspace, the category comes first. On the fixed workspace, the department comes first
[Broken workspace](https://morphyrichardsro.myvtex.com/electrocasnice)
[Fixed workspace](https://hiago--morphyrichardsro.myvtex.com/electrocasnice)
Broken:
Fixed:
=> fix IS URLs order

CHANGELOG.md, react/SearchContext.jsx
Add the `__unstableCategoryBehavior` to the `store.search` props. We will use this to control when the categoryTree will show up. The 0.x version doesn't have the support and the 1.x is still in alpha with this feature. That's why I'm using `__unstable`.
[workspace](https://categorytreebehavior--storecomponents.myvtex.com/apparel---accessories/)
- https://github.com/vtex-apps/search-graphql/pull/106
- https://github.com/vtex-apps/store-resources/pull/150
=> add categorytreebehavior to the facets query

CHANGELOG.md, react/StoreWrapper.js
Added support for Merged Service Worker
This PR adds support for the new scheme of Service Workers used in the Store app. It allows the usage of more than one Service Worker within a scope, using the feature implemented on [service-worker-graphql](https://github.com/vtex/service-worker-graphql/blob/feat/working-sw/node/middlewares/getMergedSW.ts#L102)
Once store is fully charged, check if a Service Worker called `serviceWorkerMerged.js` is successfully registered on the main scope of the page.
Workspace: ariangc
- [service-worker-graphql](https://github.com/vtex/service-worker-graphql/)
- [onesignal](https://github.com/vtex-apps/onesignal)
- [pwa-graphql](https://github.com/vtex/pwa-graphql)
=> Service Worker Merged

CHANGELOG.md, react/SearchWrapper.tsx, react/StoreWrapper.js, react/__tests__/SearchWrapper.test.ts, react/hooks/useCanonicalLink.ts, react/typings/global.d.ts, react/typings/vtex.render-runtime.d.ts
This PR adds tags for previous and next pages on the search page that have them and fixes the canonical URLs by including the page number on them.
These fixes work better on non Full Text search pages such as brand or category pages, but that is not a problem since FT pages are not indexed.
[Workspace](https://icarosearchseo--storecomponents.myvtex.com/apparel---accessories/)
Related to [https://github.com/vtex-apps/search-result/pull/516](https://github.com/vtex-apps/search-result/pull/516)
=> Improving SEO on search pages

CHANGELOG.md, react/ProductWrapper.js, react/components/ProductTitleAndPixel.tsx
This PR makes the product page compatible with the new major of the GTM app. It receives the listName via the querystring and sends it to the `productView` event.
[Workspace](https://icarogtm--storecomponents.myvtex.com/)
=> Adding list to productView GTM event

CHANGELOG.md, react/ProductWrapper.js
The product page now should receive the `listName` via runtime params. This is better than the URL approach because it doesn't conflict with other tracking methods and for the fact that if someone shares the URL with someone, now it won't incorrectly assume that the user that clicked the link came from the same shelf the user that shared the link did.
Click any shelf or search result. It should take you to the product page. Type `dataLayer` into your console, and check for the last `productDetail` event. It should have the name of the list you clicked somewhere there. The default listName for shelves is `List of products`.
[Workspace](https://icarogtm--storecomponents.myvtex.com/)
Related to [https://github.com/vtex-apps/product-summary/pull/318](https://github.com/vtex-apps/product-summar …
=> Changing product page to get listName via route params

CHANGELOG.md, react/modules/searchMetadata.ts, react/modules/searchTypes.ts
When the category tree doesn't exist, the category and department metadata were not fill
[Workspace](https://thalyta3--storecomponents.myvtex.com/apparel-accessories?map=category-1)
Before: note that in the pixel's `pageInfo` event the category and department were empty
After:
=> PER-2976: Fix metadata when categoriesTree does not exist

CHANGELOG.md, react/SearchContext.jsx
This PR solves an issue where the search page would not load the second page of results when the query contained any URI encoded character such as a space `%20`. More details on the thread [here](https://vtex.slack.com/archives/CP6S9HP46/p1636663282242700) and the jira ticket [here](url). 
We're using try/catch for the decoding because some reasonable search terms such as "100% orange juice" make the `decodeURIComponent` function throw an error, so we want to avoid that.
Go to the [master workspace](https://tackoftheday.com/) on the account `tackoftheday` and search for something with a space, like "mountain horse".  Scroll down and try to load the next page. The results will show briefly but then they'll disappear.
Now go to this [workspace](https://icarovtex--tackoftheday.myvtex.com/) …
=> Fixing search query updates due to URL decoding not being executed

CHANGELOG.md, react/StoreWrapper.js
Almost all regular pages have open graph meta tags but `store.custom` Pages doesn't have them.
This PR adds this meta tags to the pages :
`<meta property=og:type /> `
`<meta property=og:title /> `
`<meta property=og:url />` 
` <meta property=og:description />`
In this [Workspace](https://custompagesopengraph--oficinareserva.myvtex.com/) you will enter the `/vert` page and see the meta tags of the image below
Related to [#594](https://github.com/vtex-apps/store-discussion/issues/594)
=> Add Open Graph meta tags to custom Pages

CHANGELOG.md, react/modules/searchMetadata.ts
We have some searches that have the '%' on the end and this is crashing due to the decode that is made as commented on the code itself the ideia is to maintain the logic of decoding (avoiding crashing searches that need to be decoded), but also avoiding the error of URI malformed decoding an encodedURI.
[Workspace]
https://rfonseca--oceane.myvtex.com/batom%20100%?_q=batom%20100%&map=ft
https://rfonseca--mundopet.myvtex.com/ra%C3%A7%C3%A3o%20100%?_q=ra%C3%A7%C3%A3o%20100%&map=ft
https://rfonseca--gigadigital.myvtex.com/alcool%2070%?_q=alcool%2070%&map=ft
Comparing to the master workspace
=> fix: encoded term creating an URI error

CHANGELOG.md, manifest.json, react/SearchWrapper.tsx, react/components/ProductTitleAndPixel.tsx, react/modules/searchMetadata.ts, react/typings/vtex.render-runtime.d.ts, store/contentSchemas.json
- Set new settings in /admin/cms/store for SEO optimization :
- Add a #{Number} to the end of the title to avoid the title duplication issue
- Remove map parameter from canonical url. May cause issues when going to a page with facets selected. Test with caution after turning it on
- Remove store name at the end of Product and Category meta titles
[Worksapce](https://seotask2--powerplanet.myvtex.com/fundas-y-protectores-smartphone/smart?__bindingAddress=www.we-demostore.com/es&_q=smart&fuzzy=0&initialMap=ft&initialQuery=smart&map=category-2,ft&operator=and)
- Add a #{Number} to the end of the title to avoid the title duplication issue
- *Search some term, for example "smart", after, use button "Mostrar más"*
- Remove map parameter from canonical url. May cause issues when going to a page …
=> SEO optimization tasks

CHANGELOG.md, manifest.json
This enables the `bindingBounded` flag again, enabling stores to use different settings for different bindings in the same account.
Go to this [Workspace](https://victormiranda--storecomponents.myvtex.com/admin/cms/store) and check that a new `Enable configuration by binging` toggle is present in the settings form. When active, this enables users to set up configurations per binding.
This pretty much just brings back the changes from #538, but after the deployment of https://github.com/vtex/builder-hub/pull/1148.
=> Add `bindingBounded` flag to `settingsSchema`

CHANGELOG.md, react/SearchWrapper.tsx, react/modules/searchMetadata.ts
Search events were being sent without the number of results for category pages. This was affecting search reports, because these pages were being reported as empty searches.
[Workspace](https://thalyta--exitocol.myvtex.com/tecnologia/televisores)
Before (match: 0)
After (match: 797 - total products for this search)
=> Fix search metadata for category events

CHANGELOG.md, react/package.json, react/yarn.lock
We are updating dependencies to solve some security issues alerted by dependabot.
[One](https://github.com/vtex-apps/store/security/dependabot/8) of these issues is regarding `node-notifier`, but `dependabot` couldn't update it automatically.
Nothing should've changed: [workspace](https://laricia1--storecomponents.myvtex.com/)
=> Chore/Update node-notifier

CHANGELOG.md, manifest.json
Currently, the user is not able to get the value from the custom currency symbol in Trade Policy, this feature allows the user to retrieve it and now set it on the UI
Account: koestore
Product id: 1
First of all, you need to define your custom currency symbol at the trade policy screen:
`admin/Site/StoreForm.aspx?Id=1`
Set the flag `enableCustomCurrencySymbol` as true in your store search settings at: admin/cms/store
Check the product page or any other page that has the currency symbol:
[PDP with the fix:](https://iespinoza2--koestore.myvtex.com/camisa-botafogo/p) 
[PDP without the fix getting from intl:](https://master--koestore.myvtex.com/camisa-botafogo/p) 
This other PR with the feature: https://github.com/vtex-apps/format-currency/pull/29
Zendesk 590112
=> feat: use custom currency symbol from trade policy

CHANGELOG.md, react/SearchWrapper.tsx, react/__tests__/SearchWrapper.test.ts
Client `muralsyourway` uses a four-level category structure. Currently, the code that generates the canonical link for category pages is hardcoded to append a `map` query string if the category tree has more than 3 levels, resulting in a canonical like `https://muralsyourway.myvtex.com/c/animal-murals/bird-murals/owl-murals?map=c%2Cc%2Cc%2Cc`. 
This PR raises this hardcoded limit to 4. The `map` query string will still be appended if all four parts of the map are not `c`. 
Linked here: https://arthur--muralsyourway.myvtex.com/c/animal-murals/bird-murals/owl-murals
Inspect the page and compare the canonical URL to the one from master here: https://muralsyourway.myvtex.com/c/animal-murals/bird-murals/owl-murals
=> Allow 4-level category map in SearchWrapper

CHANGELOG.md, react/SearchWrapper.tsx
A US client noted two problems with their canonical URLs and open graph metatags:
- the page https://www.budgetgolf.com/black%20shoes?_q=black%20shoes&map=ft has a canonical URL that does not match the actual URL (the `_q` query string is missing from the canonical)
- the same page has an `og:url` metatag that does not match either the canonical URL or the actual URL (the `og:url` lacks any query strings)
This PR in conjunction with https://github.com/vtex-apps/open-graph/pull/33 fixes both issues.
To fix the first issue, the `_q` query param is now added to canonical URLs if it's present in the page URL.
To fix the second issue, the canonical URL generated by the `SearchWrapper` component is now passed to the `SearchOpenGraph` component as a prop, ensuring that the two metatags match. …
=> [USAAPPTEAM-727] Fix search canonical links

CHANGELOG.md, messages/id-ID.json
Add Indonesian and fix Spanish and Thai translations. Tracked by task [LOC-9012](https://vtex-dev.atlassian.net/browse/LOC-9012).
=> Add Indonesian and fix old translations

CHANGELOG.md, messages/ca.json
This feature adds a file in the "messages" directory with all the translations of this app in Català. 
For test, enter in the workspace  and disconnect the internet. Thereupon you can see a toast message with one of the translations ("Sense connexió a internet.").
[Workspace](https://xavidevelop--ametllerorigen.myvtex.com/?__bindingAddress=www.ametllerorigen.com/ca&sc=14)
Another way to translate the content of a store is overwriting the messages via GraphQL IDE (https://developers.vtex.com/docs/guides/vtex-io-documentation-overwriting-the-messages-app).
Consider that if you have made changes via GraphQL these will prevail over the files.
=> New translations in Catalan

CHANGELOG.md, react/ProfileChallenge.tsx
When mounting the redirect URL from login, the method `getLocation` ignored URL parameters and lost them.
This problem is common on pages with URI like `/checkout/orderplaced?og=09876543210978`.
=> fix: `ProfileChallenge` redirect URL not preserving query params

CHANGELOG.md, react/SearchContext.jsx
https://vtex-dev.atlassian.net/browse/SAX-53
Depends on https://github.com/vtex-apps/store-resources/pull/181
[workspace](https://thalyta--lebiscuit.myvtex.com/fritadeira?_q=fritadeira&map=ft)
* IMPORTANT: Changing the value to `sync` won't call sponsored products for all accounts, since they still have to enable the setting `fetchSponsoredProductsOnSearch`
https://github.com/vtex-apps/store-resources/assets/20840671/4808562c-ac8b-4d0e-b7f7-c28483f25892
=> SAX-53 Change sponsoredProductsBehavior default value

CHANGELOG.md, react/components/ProductTitleAndPixel.tsx
Discount not being sent in view_item event due to missing PriceWithoutDiscount in ProductViewEvent
Check dataLayer in your console
[Before](https://master--casablanca.myvtex.com/almohadon-estampado-digital-playstation-gris/p?skuId=2857)
[After](https://ccanelas--casablanca.myvtex.com/almohadon-estampado-digital-playstation-gris/p?skuId=2857)
Zendesk: #1022268
=> fix: discount not being sent in view_item

CHANGELOG.md, manifest.json, messages/ar-SA.json, messages/ar.json, messages/bg.json, messages/ca.json, messages/context.json, messages/de.json, messages/en.json, messages/es.json, messages/fr.json, messages/id-ID.json, messages/ko.json, messages/nl.json, messages/nn.json, messages/no-NO.json, messages/no.json, messages/pt.json, messages/ro.json, messages/th.json
Nowadays it's only possible to add custom headers through the settings API. The purpose of this PR is to give the possibility for the merchant or any other team to customize it through the store settings UI.
Also removed the searchTermPath since this isn't being used anymore for a while
Go to advanced tab at
[Workspace](https://customheader--storecomponents.myvtex.com/admin/cms/store)
There are some improvements that we might make in the design system when opening the modal
[Render Server 803](https://github.com/vtex/render-server/pull/803)
=> add: possibility to add more than one custom header per account

CHANGELOG.md, messages/context.json
Typo in context message keys that might affect the label translations
=> fix: typo in context message keys

CHANGELOG.md, react/SearchWrapper.tsx, react/modules/searchMetadata.ts, react/modules/searchTypes.ts
This pull request adds more information in the search metadata object: current page, products per page and a list of products (with only the `productId` field available for now).
This new information will be used by the Intelligent Search analytics app: https://github.com/vtex/sae-analytics/pull/31.
- Go to a search result page.
- Using DevTools, find the request to `https://sp.vtex.com/event-api`.
- Check the request payload: the `page`, `count` and `products` fields are created using this new information. 
[Workspace](https://felipegarcia--biggy.myvtex.com/)
Related to: https://github.com/vtex/sae-analytics/pull/31
=> Added page, maxItemsPerPage and products to search metadata

CHANGELOG.md, manifest.json
This PR adds a new flag to control bypass render runtime navigation logic, and using native browser navigation
Is related to [PR #478 in admin-pages](https://github.com/vtex-apps/admin-pages/pull/478)
[Workspace](https://paladinoteste--instoresetupqa.myvtex.com/)
* Load the workspace home
* Navigate to any PDP
* You will notice a navigation progress bar at the top of the screen, indicating that it is using Render Runtime navigation solution
* Enable the new flag "Habilitar navegação nativa do navegador" can be enabled/disabled [here](https://paladinoteste--instoresetupqa.myvtex.com/admin/cms/store)
* Wait a few minutes to avoid cached results, refresh the page, and click in the store logo, in the top left, for instance.
* Navigation progress bar should not be rendered anymore, indicating …
=> [SFSOC-95] - Add flag to enable default browser navigation

CHANGELOG.md, manifest.json
Add the `vtex.shipping-option-components@1.x` as a dependency in `manifest.json`.
This PR precede the [PR that adds a `ShippingOptionProvider` as a wrapper](https://github.com/vtex-apps/store/pull/602)
[Workspace](https://hiago--storecomponents.myvtex.com/)
=> add vtex.shipping-option-components as a dependency
